// ─────────────────────────────────────────────────────────────────────────────
// ELECTRO MANAGER — Central Data Store
// Edit this file to update all products, packs, categories, and promos.
// ─────────────────────────────────────────────────────────────────────────────

export type StockStatus = "in-stock" | "low-stock" | "out-of-stock";

export interface Product {
  id: string;
  name: string;
  category: string;
  price: number;
  originalPrice?: number;
  discount?: number;
  rating: number;
  reviews: number;
  image: string;
  hoverImage: string;
  stockStatus: StockStatus;
  inStock: boolean;
  description: string;
  specs?: Record<string, string>;
  isPromotion?: boolean;
}

export interface Pack {
  id: string;
  name: string;
  products: string[];
  images: string[];
  originalPrice: number;
  packPrice: number;
  discount: number;
  description: string;
  badge?: string;
}

export interface StoreLocation {
  id: string;
  city: string;
  address: string;
  hours: string;
  phone: string;
  mapUrl: string;
}

// ─── Categories ───────────────────────────────────────────────────────────────
export const categories = [
  "Refrigerators",
  "Washing Machines",
  "Televisions",
  "Air Fryers",
  "Coffee Machines",
  "Kitchen Appliances",
  "Ovens",
  "Dishwashers",
  "Small Appliances",
  "Cookware",
];

// ─── Products ─────────────────────────────────────────────────────────────────
export const products: Product[] = [
  // REFRIGERATORS
  {
    id: "r1",
    name: "Venizia Retro 150L Sky Blue",
    category: "Refrigerators",
    price: 2499,
    originalPrice: 2899,
    discount: 14,
    rating: 4.5,
    reviews: 48,
    image: "https://i.postimg.cc/26HfBfsB/image.png",
    hoverImage: "https://i.postimg.cc/Zq5rkBfG/Whats-App-Image-2025-08-13-22-38-07-16cf9179.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "💙 ثلاجة Venizia Retro باللون الأزرق السماوي، تصميم كلاسيكي صغير الحجم مع استهلاك منخفض للطاقة.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة Retro – بابين",
      Brand: "HENSIM",
      Capacity: "≈ 150 لتر",
      Color: "أزرق سماوي",
      Cooling: "تبريد ميكانيكي بسيط",
      Design: "ستايل Retro – مقابض معدنية",
      "Energy Class": "A",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r2",
    name: "VENEZIA Refrigerator 200L Bottom Freezer",
    category: "Refrigerators",
    price: 3299,
    originalPrice: 3799,
    discount: 13,
    rating: 4.7,
    reviews: 62,
    image: "https://i.postimg.cc/wBCCdRK0/image.png",
    hoverImage: "https://i.postimg.cc/7hDj5vZz/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧊 ثلاجة VENEZIA عملية بباب علوي للتبريد وفريزر سفلي واسع، تصميم أنيق بلون ستانلس ستيل مع توزيع مثالي للهواء للحفاظ على الأطعمة طازجة.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة بفريزر سفلي",
      Capacity: "200 لتر",
      Doors: "2 (باب علوي للتبريد + باب سفلي للفريزر)",
      Shelves: "زجاج مقوى + أدراج Big Box",
      Cooling: "Multi Air Flow – تدفق هواء متعدد",
      Color: "فضي (ستانلس ستيل)",
      Usage: "منزلي",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r3",
    name: "HENSIM MUSTANG 250L Top Freezer",
    category: "Refrigerators",
    price: 3699,
    originalPrice: 4199,
    discount: 12,
    rating: 4.5,
    reviews: 57,
    image: "https://i.postimg.cc/CK7nxPqd/Whats-App-Image-2025-08-13-22-26-05-9d707eb5.jpg",
    hoverImage: "https://i.postimg.cc/tTm1hsDj/Whats-App-Image-2025-08-13-22-34-01-f405cf58.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧊 ثلاجة HENSIM MUSTANG ببابين، سعة متوسطة مثالية للاستعمال العائلي، بنظام تبريد سريع يحافظ على الأطعمة طازجة لمدة أطول.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة ببابين – فريزر علوي",
      Brand: "HENSIM",
      Capacity: "≈ 250 لتر",
      Color: "فضي",
      Cooling: "نوفروست – بدون جليد",
      Shelves: "زجاج مقوّى",
      "Energy Class": "A+ اقتصادي",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r4",
    name: "Venizia 300L Silver",
    category: "Refrigerators",
    price: 4299,
    originalPrice: 4899,
    discount: 12,
    rating: 4.5,
    reviews: 54,
    image: "https://i.postimg.cc/wMy1F9bs/Whats-App-Image-2025-08-13-22-35-05-6be3d099.jpg",
    hoverImage: "https://i.postimg.cc/NF35zZWC/Whats-App-Image-2025-08-13-22-35-29-48f09276.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "❄️ ثلاجة Venizia باللون الفضي، فريزر علوي واسع، تصميم أنيق واستهلاك منخفض للطاقة.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة ببابين – فريزر علوي",
      Brand: "HENSIM",
      Capacity: "≈ 300 لتر",
      Color: "فضي معدني",
      Cooling: "تبريد هوائي متوازن",
      Control: "مقبض يدوي – 5 مستويات حرارة",
      "Energy Class": "A++ موفر للطاقة",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r5",
    name: "Venizia 320L Bottom Freezer Inox",
    category: "Refrigerators",
    price: 4799,
    originalPrice: 5399,
    discount: 11,
    rating: 4.5,
    reviews: 45,
    image: "https://i.postimg.cc/9F947F76/Whats-App-Image-2025-08-13-22-35-58-9e60d4a5.jpg",
    hoverImage: "https://i.postimg.cc/pLYpsGkk/Whats-App-Image-2025-08-13-22-36-16-1258f03c.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌟 ثلاجة Venizia Inox مع فريزر سفلي سهل الاستعمال، مجهزة بتقنية توزيع هواء متعدد لحفظ الأطعمة بشكل متوازن.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة ببابين – فريزر سفلي",
      Brand: "HENSIM",
      Capacity: "≈ 320 لتر",
      Color: "Inox فضي",
      Cooling: "نوفروست – متعدد الاتجاهات",
      Shelves: "3 رفوف زجاج + درج خضار",
      "Energy Class": "A+",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r6",
    name: "Venizia Side by Side 500L",
    category: "Refrigerators",
    price: 7999,
    originalPrice: 8999,
    discount: 11,
    rating: 4.5,
    reviews: 39,
    image: "https://i.postimg.cc/SKSj36v4/Whats-App-Image-2025-08-13-22-36-36-c2abba3c.jpg",
    hoverImage: "https://i.postimg.cc/Jngns947/Whats-App-Image-2025-08-13-22-36-47-7790d7d5.jpg",
    stockStatus: "low-stock",
    inStock: true,
    description: "🥶 ثلاجة Venizia كبيرة الحجم بنظام Side by Side (باب مزدوج)، سعة عالية مثالية للعائلات الكبيرة، مع شاشة تحكم رقمية.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة باب مزدوج – Side by Side",
      Brand: "HENSIM",
      Capacity: "≈ 500 لتر",
      Color: "ستانلس ستيل",
      Cooling: "نوفروست – توزيع كامل",
      Display: "Digital Control",
      "Energy Class": "A++",
      Warranty: "3 سنوات",
      Year: "2024–2025",
    },
  },
  {
    id: "r7",
    name: "Venizia Retro 200L Red",
    category: "Refrigerators",
    price: 2999,
    originalPrice: 3499,
    discount: 14,
    rating: 4.5,
    reviews: 51,
    image: "https://i.postimg.cc/VsdDrTWx/Whats-App-Image-2025-08-13-22-37-07-c80ee774.jpg",
    hoverImage: "https://i.postimg.cc/kXWNWd6p/Whats-App-Image-2025-08-13-22-37-28-7b609289.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "❤️ ثلاجة Venizia Retro بتصميم كلاسيكي باللون الأحمر، صغيرة الحجم مثالية للمطابخ العصرية أو المكاتب.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة Retro – بابين",
      Brand: "HENSIM",
      Capacity: "≈ 200 لتر",
      Color: "أحمر",
      Cooling: "تبريد ميكانيكي",
      Design: "ستايل Retro – مقابض كروم",
      "Energy Class": "A",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r8",
    name: "VENEZIA Refrigerator 420L Inverter",
    category: "Refrigerators",
    price: 5999,
    originalPrice: 6799,
    discount: 12,
    rating: 4.7,
    reviews: 66,
    image: "https://i.postimg.cc/8PLj8Mqn/image.png",
    hoverImage: "https://i.postimg.cc/HLNp8kqy/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "❄️ ثلاجة VENEZIA بسعة 420 لتر، تصميم أنيق باللون Inox، مزودة بتقنية Inverter لتوفير الطاقة، تبريد سريع وهادئ مع فريزر علوي واسع. مثالية للعائلات الحديثة.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة بفريزر علوي",
      Capacity: "420 لتر",
      Dimensions: "185 × 70 × 67 سم",
      "Energy Class": "A+ موفر للطاقة",
      Cooling: "No Frost (بدون ثلج)",
      Technology: "Inverter – هدوء وتوفير كهرباء",
      Color: "Inox فضي",
      Warranty: "3 سنوات",
      Year: "2024–2025",
    },
  },
  {
    id: "r9",
    name: "Venizia Retro 200L Classic Red",
    category: "Refrigerators",
    price: 3099,
    originalPrice: 3599,
    discount: 14,
    rating: 4.5,
    reviews: 43,
    image: "https://i.postimg.cc/nzsBr8fT/Whats-App-Image-2025-08-13-22-38-20-4011f253.jpg",
    hoverImage: "https://i.postimg.cc/0jDSGpQw/Whats-App-Image-2025-08-13-22-38-47-9cc95256.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "❤️ ثلاجة Venizia Retro باللون الأحمر الكلاسيكي، تصميم أنيق مع حجم متوسط مثالي للمطابخ العصرية والمكاتب، مزودة بفريزر علوي صغير واستهلاك طاقة منخفض.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة Retro – بابين",
      Brand: "HENSIM",
      Capacity: "≈ 200 لتر",
      Color: "أحمر كلاسيكي",
      Freezer: "علوي – مدمج",
      Cooling: "تبريد ميكانيكي سريع",
      Design: "ستايل Retro مع مقابض معدنية",
      "Energy Class": "A اقتصادي",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "r10",
    name: "Venizia Retro 200L Turquoise",
    category: "Refrigerators",
    price: 3099,
    originalPrice: 3599,
    discount: 14,
    rating: 4.5,
    reviews: 47,
    image: "https://i.postimg.cc/xTGHcyBr/Whats-App-Image-2025-08-13-22-39-05-c8a5d2ae.jpg",
    hoverImage: "https://i.postimg.cc/bv5SK6Sn/Whats-App-Image-2025-08-13-22-39-23-cd04227f.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "💙 ثلاجة Venizia Retro باللون الأزرق السماوي (تركواز)، تصميم عصري-كلاسيكي صغير الحجم، مثالية للشقق أو المكاتب، مجهزة بفريزر علوي وتقنية تبريد فعّالة.",
    specs: {
      Condition: "جديد",
      Type: "ثلاجة Retro – بابين",
      Brand: "HENSIM",
      Capacity: "≈ 200 لتر",
      Color: "أزرق سماوي",
      Freezer: "علوي – مدمج",
      Cooling: "تبريد ميكانيكي",
      Design: "ستايل Retro مع مقابض كروم",
      "Energy Class": "A اقتصادي",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },

  // WASHING MACHINES
  {
    id: "w1",
    name: "VENEZIA R1000 Front Load 9kg Steam",
    category: "Washing Machines",
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.3,
    reviews: 58,
    image: "https://i.postimg.cc/3JrQFW80/image.png",
    hoverImage: "https://i.postimg.cc/3JrQFW80/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧺 غسالة VENEZIA R1000 سعة 9 كغ، تقنية البخار Steam تعقيم حتى 99.9% للقضاء على الجراثيم والمواد المسببة للحساسية، موتور BLDC هادئ واقتصادي مع 10 سنوات ضمان.",
    specs: {
      Condition: "جديد",
      Type: "غسالة أمامية أوتوماتيكية",
      Brand: "VENEZIA",
      RPM: "1400 دورة/دقيقة",
      Technology: "Steam™ – عناية ضد الحساسية",
      Motor: "BLDC إنفرتر – اقتصادي وصامت",
      Display: "LED رقمية",
      Warranty: "10 سنوات على الموتور – سنتان شامل",
      Year: "2025",
      SizesPrices: "5kg 2699dh | 7kg 2999dh | 9kg 3499dh | 11kg 3699dh | 13kg 4199dh",
    },
  },
  {
    id: "w2",
    name: "VENEZIA X1000 Front Load 10kg",
    category: "Washing Machines",
    price: 3699,
    originalPrice: 4199,
    discount: 12,
    rating: 4.5,
    reviews: 64,
    image: "https://i.postimg.cc/WbN23XxZ/image.png",
    hoverImage: "https://i.postimg.cc/WbN23XxZ/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ غسالة VENEZIA X1000 سعة 10 كغ، موتور رقمي ذكي Smart Digital Motor، شاشة LED متطورة، كفاءة عالية مع برامج متعددة للغسيل السريع والاقتصادي.",
    specs: {
      Condition: "جديد",
      Type: "غسالة أمامية أوتوماتيكية",
      Brand: "VENEZIA",
      RPM: "1400 دورة/دقيقة",
      Technology: "Smart Digital Motor + Eco Wash",
      Motor: "BLDC إنفرتر – اقتصادي وصامت",
      Display: "LED رقمية",
      Warranty: "10 سنوات على الموتور – سنتان شامل",
      Year: "2025",
      SizesPrices: "5kg 2699dh | 7kg 2999dh | 9kg 3499dh | 11kg 3699dh | 13kg 4199dh",
    },
  },
  {
    id: "w3",
    name: "VENEZIA X1000 Allergy Care 8kg",
    category: "Washing Machines",
    price: 2999,
    originalPrice: 3399,
    discount: 12,
    rating: 4.5,
    reviews: 49,
    image: "https://i.postimg.cc/rmbthQQG/Whats-App-Image-2025-08-14-16-50-30-3e6cf430.jpg",
    hoverImage: "https://i.postimg.cc/rmbthQQG/Whats-App-Image-2025-08-14-16-50-30-3e6cf430.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌿 غسالة VENEZIA X1000 Allergy Care بسعة 8 كغ، معالجة ضد مسببات الحساسية مع برنامج تعقيم بالبخار، موتور BLDC اقتصادي، مثالية للعائلات المتوسطة.",
    specs: {
      Condition: "جديد",
      Type: "غسالة أمامية أوتوماتيكية",
      Brand: "VENEZIA",
      RPM: "1400 دورة/دقيقة",
      Technology: "Allergy Care + Steam",
      Motor: "BLDC هادئ واقتصادي",
      Display: "LED رقمية",
      Warranty: "10 سنوات على الموتور – سنتان شامل",
      Year: "2025",
      SizesPrices: "5kg 2699dh | 7kg 2999dh | 9kg 3499dh | 11kg 3699dh | 13kg 4199dh",
    },
  },
  {
    id: "w4",
    name: "VENEZIA Front Load 9kg Steam Wash",
    category: "Washing Machines",
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.5,
    reviews: 53,
    image: "https://i.postimg.cc/nzGyftFP/image.png",
    hoverImage: "https://i.postimg.cc/nzGyftFP/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧺 غسالة أمامية VENEZIA بسعة 9 كغ، تقنية Steam Wash لإزالة البقع والجراثيم حتى 99%، موتور BLDC إنفرتر اقتصادي وهادئ مع شاشة LED رقمية.",
    specs: {
      Condition: "جديد",
      Type: "غسالة أمامية أوتوماتيكية",
      Brand: "VENEZIA",
      RPM: "1400 دورة/دقيقة",
      Technology: "Steam Wash + Allergy Care",
      Motor: "BLDC إنفرتر",
      Display: "LED رقمية",
      Warranty: "10 سنوات على الموتور – سنتان شامل",
      Year: "2025",
      SizesPrices: "5kg 2699dh | 7kg 2999dh | 9kg 3499dh | 11kg 3699dh | 13kg 4199dh",
    },
  },
  {
    id: "w5",
    name: "VENEZIA Dishwasher 13 Couverts Silver",
    category: "Washing Machines",
    price: 3199,
    originalPrice: 3699,
    discount: 14,
    rating: 4.5,
    reviews: 37,
    image: "https://i.postimg.cc/PqwHccvg/image.png",
    hoverImage: "https://i.postimg.cc/PqwHccvg/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥂 جلاية أواني VENEZIA باللون الفضي الأنيق، سعة 12 طقم، 6 برامج شاملة مع خاصية نصف الحمولة لتوفير الماء والكهرباء.",
    specs: {
      Condition: "جديد",
      Type: "غسالة أواني أوتوماتيكية",
      Brand: "VENEZIA",
      Model: "DW-12 Silver",
      Capacity: "13 Couverts",
      Programs: "6 (اقتصادي – مكثف – سريع – نصف حمولة)",
      "Energy Class": "A++",
      NoiseLevel: "≤ 49 ديسبل",
      WaterConsumption: "≈ 10 لتر/دورة",
      SizesPrices: "Sans Chichoire 3199dh | Avec Chichoire 3699dh",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "w6",
    name: "VENEZIA Top Load Semi Automatic 8kg Flower",
    category: "Washing Machines",
    price: 799,
    originalPrice: 949,
    discount: 16,
    rating: 4.5,
    reviews: 72,
    image: "https://i.postimg.cc/wj0QpK2g/Whats-App-Image-2025-08-14-16-53-07-a1ed0070.jpg",
    hoverImage: "https://i.postimg.cc/wj0QpK2g/Whats-App-Image-2025-08-14-16-53-07-a1ed0070.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌸 غسالة VENEZIA علوية بسعة 8 كغ، تصميم أنيق مع ديكور أزهار، اقتصادية ومناسبة للاستعمال العائلي اليومي.",
    specs: {
      Condition: "جديد",
      Type: "غسالة علوية نصف أوتوماتيك",
      Brand: "VENEZIA",
      Model: "Top 8kg Flower",
      Capacity: "8 كغ",
      Programs: "غسيل – شطف – عصر",
      Material: "بلاستيك مقوى + غطاء شفاف",
      Warranty: "سنة",
      Year: "2024–2025",
      PriceSize: "799dh",
    },
  },
  {
    id: "w7",
    name: "VENEZIA Top Load Semi Automatic 7kg Mini",
    category: "Washing Machines",
    price: 849,
    originalPrice: 999,
    discount: 15,
    rating: 4.5,
    reviews: 61,
    image: "https://i.postimg.cc/PfYbqvy6/Whats-App-Image-2025-08-14-17-00-17-31b550b1.jpg",
    hoverImage: "https://i.postimg.cc/PfYbqvy6/Whats-App-Image-2025-08-14-17-00-17-31b550b1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ غسالة VENEZIA صغيرة الحجم بسعة 7 كغ، مثالية للاستعمال الفردي أو العائلي الصغير، سهلة الاستعمال والتنقل.",
    specs: {
      Condition: "جديد",
      Type: "غسالة علوية نصف أوتوماتيك",
      Brand: "VENEZIA",
      Model: "Top 7kg Mini",
      Capacity: "7 كغ",
      Programs: "غسيل + عصر",
      Material: "بلاستيك مقوى",
      Warranty: "سنة",
      Year: "2024–2025",
      PriceSize: "849dh",
    },
  },

  // TELEVISIONS
  {
    id: "t1",
    name: 'VENEZIA Google TV 75" 4K QLED GTV75',
    category: "Televisions",
    price: 7999,
    originalPrice: 8999,
    discount: 11,
    rating: 4.8,
    reviews: 124,
    image: "https://i.postimg.cc/76YW2kss/Whats-App-Image-2025-08-13-23-14-17-f27182fe.jpg",
    hoverImage: "https://i.postimg.cc/YCTrRXKz/Whats-App-Image-2025-08-13-23-09-42-cc41476d.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "📺 تلفاز VENEZIA Google TV 75 بوصة – شاشة 4K QLED بجودة صورة عالية وألوان واقعية، مزود بنظام Android 12 وWiFi 5، مثالي لمشاهدة الأفلام والمسلسلات مع Dolby Audio وتطبيقات ترفيهية مثل Netflix وYouTube وDisney+.",
    specs: {
      Condition: "جديد",
      Type: "تلفاز ذكي 4K QLED – Google TV",
      Brand: "VENEZIA",
      Model: "GTV75",
      Resolution: "دقة 4K Ultra HD",
      System: "Google TV – Android 12 – WiFi 5",
      Connectivity: "4 مداخل HDMI، 2 منافذ USB، بلوتوث، Chromecast مدمج",
      Size: '75"',
      Warranty: "سنتان",
      Year: "2025",
    },
  },
  {
    id: "t2",
    name: 'VENEZIA Google TV 4K QLED 55" GTV95',
    category: "Televisions",
    price: 12999,
    originalPrice: 14999,
    discount: 13,
    rating: 4.5,
    reviews: 96,
    image: "https://i.postimg.cc/j2sk7z7Q/Whats-App-Image-2025-08-13-23-08-33-9019ba30.jpg",
    hoverImage: "https://i.postimg.cc/YCTrRXKz/Whats-App-Image-2025-08-13-23-09-42-cc41476d.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "📺 تلفاز VENEZIA Google TV 4K QLED بتصميم أنيق وجودة صورة فائقة – مثالي للترفيه العائلي مع أحدث التقنيات مثل Netflix وYouTube وPrime Video وDisney+.",
    specs: {
      Condition: "جديد",
      Type: "تلفاز 4K QLED – Google TV",
      Brand: "VENEZIA",
      Model: "GTV95",
      Resolution: "دقة 4K Ultra HD",
      System: "نظام Google TV – WiFi 5",
      Connectivity: "4 مداخل HDMI، 2 منافذ USB، بلوتوث، Chromecast مدمج",
      Size: '55"',
      Warranty: "سنتان",
      Year: "2025",
    },
  },
  {
    id: "t3",
    name: 'KÖLN Android 14 Smart TV 32" KH32SM',
    category: "Televisions",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.6,
    reviews: 178,
    image: "https://i.postimg.cc/sD9Hwxk6/Whats-App-Image-2025-08-13-23-24-11-ab721ddf.jpg",
    hoverImage: "https://i.postimg.cc/Pr4K1cD0/Whats-App-Image-2025-08-13-23-48-32-f1918354.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "📺 تلفاز KÖLN Android 14 ذكي بحجم 32 بوصة – تصميم أنيق وأداء موثوق، مزود بنظام Android 14 مع تطبيقات ترفيهية حديثة، مثالي للغرف الصغيرة والاستخدام اليومي.",
    specs: {
      Condition: "جديد",
      Type: "تلفاز ذكي LED – Android TV",
      Brand: "KÖLN",
      Model: "KH32SM",
      Resolution: "دقة HD",
      System: "Android 14",
      Connectivity: "3 مداخل HDMI، 2 منافذ USB",
      Size: '32"',
      Warranty: "سنتان",
      Year: "2025",
    },
  },

  // AIR FRYERS
  {
    id: "af1",
    name: "Vospeed Stand Mixer 5.5L",
    category: "Air Fryers",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    rating: 4.7,
    reviews: 81,
    image: "https://i.postimg.cc/W1Xgdxsk/Whats-App-Image-2025-08-26-01-17-40-257a67df.jpg",
    hoverImage: "https://i.postimg.cc/W1Xgdxsk/Whats-App-Image-2025-08-26-01-17-40-257a67df.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍞 عجانة كهربائية Vospeed Stand Mixer قوية وفعالة لتحضير جميع أنواع العجائن والخبز والحلويات. تأتي بوعاء ستانلس ستيل متين وتصميم أنيق باللون الكريمي مع أمان عالي وسهولة في الاستعمال.",
    specs: {
      Condition: "جديد",
      Type: "عجانة كهربائية (Stand Mixer)",
      Model: "Vospeed Classic",
      Color: "كريمي",
      Capacity: "5.5 لتر",
      Power: "1000 واط",
      Bowl: "ستانلس ستيل مقاوم للصدأ مع غطاء حماية",
      Speeds: "6 سرعات + خاصية Pulse",
      Accessories: "خطاف للعجين، مضرب مسطح، مضرب سلكي",
      Safety: "مانع انزلاق + نظام حماية من الحرارة",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "af2",
    name: "VENEZIA Stand Mixer Premium Glass Bowl 5L",
    category: "Air Fryers",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    rating: 4.8,
    reviews: 73,
    image: "https://i.postimg.cc/MG0k00rV/Whats-App-Image-2025-08-26-01-21-29-71bac148.jpg",
    hoverImage: "https://i.postimg.cc/MG0k00rV/Whats-App-Image-2025-08-26-01-21-29-71bac148.jpg",
    stockStatus: "low-stock",
    inStock: true,
    description: "✨ عجانة كهربائية Venezia Stand Mixer بتصميم فاخر باللون الأسود مع لمسة ذهبي وردي. مزودة بوعاء زجاجي محفّر متين، مثالية للعجن والخبز والحلويات.",
    specs: {
      Condition: "جديد",
      Type: "عجانة كهربائية (Stand Mixer)",
      Model: "Venezia Premium Glass Bowl",
      Color: "أسود × ذهبي وردي",
      Capacity: "5 لتر",
      Power: "1200 واط",
      Bowl: "زجاجي مقاوم للحرارة محفّر مع غطاء حماية",
      Speeds: "6 سرعات + خاصية Pulse",
      Accessories: "خطاف للعجين، مضرب سلكي، مضرب مسطح",
      Safety: "نظام حماية من الحرارة + مانع انزلاق",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "af3",
    name: "VENEZIA Air Fryer 3L",
    category: "Air Fryers",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    rating: 4.6,
    reviews: 86,
    image: "https://i.postimg.cc/BvDS935V/Whats-App-Image-2025-08-16-01-28-07-c6c43117.jpg",
    hoverImage: "https://i.postimg.cc/BvDS935V/Whats-App-Image-2025-08-16-01-28-07-c6c43117.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍟 قلاية هوائية بسعة 3 لتر، تقلل استهلاك الزيت بنسبة 85%، مزودة بترموستات قابل للتعديل وطبقة مانعة للالتصاق.",
    specs: {
      Condition: "جديد",
      Type: "قلاية هوائية – Air Fryer",
      Capacity: "3 لتر",
      Power: "1500 واط",
      Features: "مؤقت 30 دقيقة، ترموستات حتى 200°C",
      Color: "أسود × Inox",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "af4",
    name: "VENEZIA Air Fryer Digital 5L",
    category: "Air Fryers",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    rating: 4.6,
    reviews: 112,
    image: "https://i.postimg.cc/dQnqK4dw/Whats-App-Image-2025-08-16-01-42-46-9cf2c3db.jpg",
    hoverImage: "https://i.postimg.cc/dQnqK4dw/Whats-App-Image-2025-08-16-01-42-46-9cf2c3db.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍟 قلاية هوائية بسعة 5 لتر، مثالية للعائلات، شاشة رقمية مع برامج طهي مسبقة الإعداد.",
    specs: {
      Condition: "جديد",
      Type: "قلاية هوائية – Air Fryer",
      Capacity: "5 لتر",
      Power: "1700 واط",
      Features: "شاشة رقمية، 7 برامج طهي",
      Color: "أسود",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },

  // COFFEE MACHINES
  {
    id: "c1",
    name: "KOLN Espresso Machine 15 Bar",
    category: "Coffee Machines",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.6,
    reviews: 53,
    image: "https://i.postimg.cc/wBKzkPKc/Whats-App-Image-2025-08-16-01-48-24-01fbfdc2.jpg",
    hoverImage: "https://i.postimg.cc/wBKzkPKc/Whats-App-Image-2025-08-16-01-48-24-01fbfdc2.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "☕ ماكينة قهوة KÖLN Expresso كلاسيكية بضغط 15 بار، مثالية لتحضير الإسبريسو والكابتشينو في المنزل بجودة عالية.",
    specs: {
      Condition: "جديد",
      Type: "ماكينة قهوة Expresso",
      Pressure: "15 بار",
      Tank: "1.5 لتر",
      Color: "Inox × أسود",
      Features: "بخار للحليب + فلتر مزدوج",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "c2",
    name: "VENEZIA Capsule Coffee Machine",
    category: "Coffee Machines",
    price: 899,
    originalPrice: 1099,
    discount: 18,
    rating: 4.6,
    reviews: 48,
    image: "https://i.postimg.cc/HLZFHmBx/Whats-App-Image-2025-08-16-01-51-39-dfb75095.jpg",
    hoverImage: "https://i.postimg.cc/HLZFHmBx/Whats-App-Image-2025-08-16-01-51-39-dfb75095.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "☕ ماكينة قهوة VENEZIA بالكبسولات، تصميم صغير الحجم أنيق، مثالية للاستعمال السريع في المنزل أو المكتب.",
    specs: {
      Condition: "جديد",
      Type: "ماكينة قهوة بالكبسولات",
      Tank: "0.8 لتر",
      Color: "أسود لامع",
      Features: "تشغيل أوتوماتيكي + صامتة",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "c3",
    name: "KOLN Espresso Pro Touch 20 Bar",
    category: "Coffee Machines",
    price: 2499,
    originalPrice: 2899,
    discount: 14,
    rating: 4.6,
    reviews: 39,
    image: "https://i.postimg.cc/8C9wtzZh/Whats-App-Image-2025-08-16-02-08-03-988e4bbe.jpg",
    hoverImage: "https://i.postimg.cc/8C9wtzZh/Whats-App-Image-2025-08-16-02-08-03-988e4bbe.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "☕ ماكينة قهوة KÖLN Expresso Pro بشاشة لمس و20 برنامج، ضغط 20 بار مع طحن مباشر، تجربة احترافية لعشاق القهوة.",
    specs: {
      Condition: "جديد",
      Type: "ماكينة قهوة Expresso احترافية",
      Pressure: "20 بار",
      Tank: "2 لتر",
      Color: "Inox × أسود",
      Features: "شاشة لمس، برامج أوتوماتيكية",
      Warranty: "3 سنوات",
      Year: "2024–2025",
    },
  },
  {
    id: "c4",
    name: "KOLN Automatic Espresso Machine Grinder 20 Bar",
    category: "Coffee Machines",
    price: 2299,
    originalPrice: 2699,
    discount: 15,
    rating: 4.6,
    reviews: 35,
    image: "https://i.postimg.cc/K8c9YVKg/Whats-App-Image-2025-08-16-02-03-16-92fb5d84.jpg",
    hoverImage: "https://i.postimg.cc/K8c9YVKg/Whats-App-Image-2025-08-16-02-03-16-92fb5d84.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "☕ ماكينة قهوة KÖLN Expresso أوتوماتيكية مع مطحنة مدمجة، ضغط 20 بار لتحضير الإسبريسو والكابتشينو بجودة احترافية.",
    specs: {
      Condition: "جديد",
      Type: "ماكينة قهوة Expresso أوتوماتيكية",
      Pressure: "20 بار",
      Tank: "2 لتر",
      Color: "أسود × Inox",
      Features: "مطحنة مدمجة + بخار للحليب",
      Warranty: "3 سنوات",
      Year: "2024–2025",
    },
  },

  // KITCHEN APPLIANCES
  {
    id: "k1",
    name: "VENEZIA Industrial Vacuum Cleaner 20L",
    category: "Kitchen Appliances",
    price: 1199,
    originalPrice: 1399,
    discount: 14,
    rating: 4.7,
    reviews: 42,
    image: "https://i.postimg.cc/8cQGQDzv/Whats-App-Image-2025-08-19-15-40-08-f3329ac0.jpg",
    hoverImage: "https://i.postimg.cc/8cQGQDzv/Whats-App-Image-2025-08-19-15-40-08-f3329ac0.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧹 مكنسة كهربائية صناعية بسعة 20 لتر للسوائل والغبار، مثالية للاستعمال في الورشات والمنازل، قوة شفط عالية مع خزان ستانلس ستيل متين.",
    specs: {
      Condition: "جديد",
      Type: "مكنسة صناعية – ماء وغبار",
      Capacity: "20 لتر",
      Power: "1600 واط",
      Material: "خزان ستانلس ستيل",
      Usage: "ماء + غبار",
      Wheels: "٤ عجلات للحركة السهلة",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k8",
    name: "VENEZIA Water Purifier 5 Stages",
    category: "Kitchen Appliances",
    price: 1699,
    originalPrice: 1999,
    discount: 15,
    rating: 4.6,
    reviews: 31,
    image: "https://i.postimg.cc/BZHs58mB/Whats-App-Image-2025-08-16-02-16-58-eec921de.jpg",
    hoverImage: "https://i.postimg.cc/BZHs58mB/Whats-App-Image-2025-08-16-02-16-58-eec921de.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "💧 جهاز تنقية المياه VENEZIA بخمس مراحل، يزيل الشوائب والكلور والروائح لضمان مياه نقية وصالحة للشرب.",
    specs: {
      Condition: "جديد",
      Type: "فلتر مياه منزلي – 5 مراحل",
      Capacity: "75 GPD",
      Stages: "فلتر رسوبي، كربوني، RO، UV، معدني",
      Color: "أبيض",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k9",
    name: "KOLN Home Vacuum Cleaner 2L",
    category: "Kitchen Appliances",
    price: 849,
    originalPrice: 999,
    discount: 15,
    rating: 4.6,
    reviews: 57,
    image: "https://i.postimg.cc/jdTTMs90/Whats-App-Image-2025-08-19-15-39-27-470381b0.jpg",
    hoverImage: "https://i.postimg.cc/jdTTMs90/Whats-App-Image-2025-08-19-15-39-27-470381b0.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🧹 مكنسة كهربائية KÖLN قوية وصغيرة الحجم، مثالية لتنظيف المنازل بفضل فلاتر متعددة وملحقات متنوعة.",
    specs: {
      Condition: "جديد",
      Type: "مكنسة كهربائية منزلية",
      Power: "1800 واط",
      Filter: "HEPA قابل للغسل",
      Capacity: "2 لتر",
      Accessories: "فرشاة أرضية + فرشاة زاوية",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k10",
    name: "VENEZIA Gas Water Heater 6L",
    category: "Kitchen Appliances",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.6,
    reviews: 27,
    image: "https://i.postimg.cc/pXCwkKzz/Whats-App-Image-2025-08-19-15-45-17-3f35a00f.jpg",
    hoverImage: "https://i.postimg.cc/pXCwkKzz/Whats-App-Image-2025-08-19-15-45-17-3f35a00f.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 سخان مياه غازي VENEZIA بسعة 6 لتر، اقتصادي في استهلاك الغاز مع نظام أمان ضد تسرب الغاز.",
    specs: {
      Condition: "جديد",
      Type: "سخان مياه غازي",
      Capacity: "6 لتر",
      Power: "Gaz Butane/Propane",
      Safety: "صمام أمان أوتوماتيكي",
      Color: "أبيض",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k11",
    name: "KOLN Electric Water Heater 50L",
    category: "Kitchen Appliances",
    price: 1899,
    originalPrice: 2199,
    discount: 14,
    rating: 4.6,
    reviews: 24,
    image: "https://i.postimg.cc/g2BfbdM0/image.png",
    hoverImage: "https://i.postimg.cc/g2BfbdM0/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "💧 سخان مياه كهربائي KÖLN بسعة 50 لتر، مجهز بخاصية التحكم في الحرارة وطبقة عزل حراري متطورة.",
    specs: {
      Condition: "جديد",
      Type: "سخان مياه كهربائي",
      Capacity: "50 لتر",
      Power: "2000 واط",
      Safety: "ثرموستات مع حماية ضد الحرارة الزائدة",
      Color: "أبيض",
      Warranty: "3 سنوات",
      Year: "2024–2025",
    },
  },
  {
    id: "k12",
    name: "VENEZIA Kitchen Hood Inox 60cm",
    category: "Kitchen Appliances",
    price: 1399,
    originalPrice: 1599,
    discount: 13,
    rating: 4.6,
    reviews: 29,
    image: "https://i.postimg.cc/d1GXCCJ7/Whats-App-Image-2025-08-19-17-35-46-87b2b850.jpg",
    hoverImage: "https://i.postimg.cc/d1GXCCJ7/Whats-App-Image-2025-08-19-17-35-46-87b2b850.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍳 شفاط مطبخ VENEZIA Inox بقوة شفط عالية، مزود بفلتر كربوني لإزالة الروائح والدهون.",
    specs: {
      Condition: "جديد",
      Type: "شفاط مطبخ جداري",
      Power: "450 م³/ساعة",
      Filter: "كربوني + معدني",
      Dimensions: "60 سم",
      Color: "Inox",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k13",
    name: "KOLN Stand Fan Adjustable",
    category: "Kitchen Appliances",
    price: 349,
    originalPrice: 429,
    discount: 19,
    rating: 4.6,
    reviews: 43,
    image: "https://i.postimg.cc/4x3r0nQM/Whats-App-Image-2025-08-19-15-38-49-a3aad600.jpg",
    hoverImage: "https://i.postimg.cc/4x3r0nQM/Whats-App-Image-2025-08-19-15-38-49-a3aad600.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌬️ مروحة KÖLN قائمة بارتفاع قابل للتعديل، بثلاث سرعات وتوزيع هواء فعال.",
    specs: {
      Condition: "جديد",
      Type: "مروحة قائمة",
      Speeds: "3 مستويات",
      Power: "60 واط",
      Safety: "شبك معدني آمن",
      Color: "أسود × أبيض",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k14",
    name: "KOLN Stand Fan 16 Inch",
    category: "Kitchen Appliances",
    price: 399,
    originalPrice: 479,
    discount: 17,
    rating: 4.6,
    reviews: 39,
    image: "https://i.postimg.cc/65WS7Tg3/Whats-App-Image-2025-08-19-17-42-46-b72b024c.jpg",
    hoverImage: "https://i.postimg.cc/65WS7Tg3/Whats-App-Image-2025-08-19-17-42-46-b72b024c.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌬️ مروحة KÖLN قائمة بقطر 16 بوصة، بارتفاع قابل للتعديل و3 سرعات لتوزيع مثالي للهواء.",
    specs: {
      Condition: "جديد",
      Type: "مروحة قائمة – Stand Fan",
      Diameter: "16 بوصة",
      Speeds: "3",
      Power: "60 واط",
      Safety: "شبك معدني آمن",
      Color: "أسود / أبيض",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k15",
    name: "KOLN Floor Fan 20 Inch",
    category: "Kitchen Appliances",
    price: 549,
    originalPrice: 649,
    discount: 15,
    rating: 4.6,
    reviews: 34,
    image: "https://i.postimg.cc/W1tHnC2c/Whats-App-Image-2025-08-19-17-47-42-73910db1.jpg",
    hoverImage: "https://i.postimg.cc/W1tHnC2c/Whats-App-Image-2025-08-19-17-47-42-73910db1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌪️ مروحة أرضية معدنية KÖLN قوية مع 3 سرعات، مثالية للمساحات الكبيرة والتهوية القوية.",
    specs: {
      Condition: "جديد",
      Type: "مروحة أرضية – Floor Fan",
      Diameter: "20 بوصة",
      Speeds: "3",
      Power: "120 واط",
      Safety: "شبك معدني قوي",
      Color: "فضي",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k16",
    name: "VENEZIA Electric Barbecue 70cm",
    category: "Kitchen Appliances",
    price: 799,
    originalPrice: 949,
    discount: 16,
    rating: 4.6,
    reviews: 26,
    image: "https://i.postimg.cc/qRcbqdGy/Whats-App-Image-2025-08-19-17-39-35-a2eaddfc.jpg",
    hoverImage: "https://i.postimg.cc/qRcbqdGy/Whats-App-Image-2025-08-19-17-39-35-a2eaddfc.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥩 شواية كهربائية VENEZIA بطول 70 سم، مثالية للعائلات، توزيع حراري متساوي وصينية قابلة للفك والتنظيف.",
    specs: {
      Condition: "جديد",
      Type: "شواية كهربائية – Barbecue",
      Length: "70 سم",
      Power: "2000 واط",
      Surface: "مضاد للالتصاق",
      Cleaning: "سهل – صينية قابلة للفك",
      Color: "أسود",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k17",
    name: "VENEZIA Citrus Juicer 0.7L",
    category: "Kitchen Appliances",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.6,
    reviews: 31,
    image: "https://i.postimg.cc/Pf4VkTJk/Whats-App-Image-2025-08-16-02-11-44-41628c16.jpg",
    hoverImage: "https://i.postimg.cc/Pf4VkTJk/Whats-App-Image-2025-08-16-02-11-44-41628c16.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍊 عصارة كهربائية VENEZIA للحمضيات بقدرة 40 واط، مثالية لتحضير العصائر الطازجة بسرعة.",
    specs: {
      Condition: "جديد",
      Type: "عصارة كهربائية – Citrus Juicer",
      Capacity: "0.7 لتر",
      Power: "40 واط",
      Features: "فوهة سكب مباشرة + أجزاء قابلة للغسل",
      Color: "أخضر / برتقالي",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k18",
    name: "KOLN Hand Blender 4 in 1 600W",
    category: "Kitchen Appliances",
    price: 449,
    originalPrice: 549,
    discount: 18,
    rating: 4.6,
    reviews: 47,
    image: "https://i.postimg.cc/nzx26Ptz/Whats-App-Image-2025-08-15-11-00-28-dee8de0e.jpg",
    hoverImage: "https://i.postimg.cc/nzx26Ptz/Whats-App-Image-2025-08-15-11-00-28-dee8de0e.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط يدوي KÖLN متعدد الوظائف 4 في 1 (خلاط، خافق، مفرمة، كوب قياس) بقوة 600 واط.",
    specs: {
      Condition: "جديد",
      Type: "خلاط يدوي – Mixeur Plongeant",
      Power: "600 واط",
      Accessories: "خافق، مفرمة، كوب قياس",
      Blades: "ستانلس ستيل",
      Color: "أسود × Inox",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k19",
    name: "KOLN Pro Inox Blender 2L",
    category: "Kitchen Appliances",
    price: 599,
    originalPrice: 729,
    discount: 18,
    rating: 4.6,
    reviews: 36,
    image: "https://i.postimg.cc/DfB6M6pv/Whats-App-Image-2025-08-15-11-04-03-ef568ce0.jpg",
    hoverImage: "https://i.postimg.cc/DfB6M6pv/Whats-App-Image-2025-08-15-11-04-03-ef568ce0.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط KÖLN Pro Inox مع وعاء ستانلس ستيل بسعة كبيرة، مثالي للعجين والخلط الثقيل، مزود بشفرات قوية من الفولاذ المقاوم للصدأ.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي – وعاء ستانلس",
      Capacity: "2 لتر",
      Power: "700 واط",
      Blades: "ستانلس ستيل",
      Speeds: "متعددة",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k20",
    name: "KOLN Classic Blender 1.5L",
    category: "Kitchen Appliances",
    price: 299,
    originalPrice: 379,
    discount: 21,
    rating: 4.6,
    reviews: 41,
    image: "https://i.postimg.cc/W3sm9qMq/Whats-App-Image-2025-08-15-11-08-05-e618584a.jpg",
    hoverImage: "https://i.postimg.cc/W3sm9qMq/Whats-App-Image-2025-08-15-11-08-05-e618584a.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط KÖLN كلاسيكي مع كأس زجاجي سعة 1.5 لتر، مثالي للعصائر والخلطات اليومية.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي كلاسيكي",
      Capacity: "1.5 لتر",
      Power: "400 واط",
      Blades: "ستانلس ستيل",
      Color: "أبيض × أزرق",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k21",
    name: "VENEZIA Blender 1.5L Inox Silver",
    category: "Kitchen Appliances",
    price: 349,
    originalPrice: 429,
    discount: 19,
    rating: 4.6,
    reviews: 33,
    image: "https://i.postimg.cc/FzRyvtC9/Whats-App-Image-2025-08-15-11-13-32-3aa1ff62.jpg",
    hoverImage: "https://i.postimg.cc/FzRyvtC9/Whats-App-Image-2025-08-15-11-13-32-3aa1ff62.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط VENEZIA أنيق مع كأس زجاجي مقاوم للصدمات، شفرات حادة من الستانلس ستيل، مثالي للعصائر والكوكتيلات.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي",
      Capacity: "1.5 لتر",
      Power: "450 واط",
      Blades: "ستانلس ستيل – 4 شفرات",
      Color: "Inox × فضي",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k22",
    name: "KOLN Inox Premium Blender 1.5L",
    category: "Kitchen Appliances",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.6,
    reviews: 28,
    image: "https://i.postimg.cc/2jcdw633/Whats-App-Image-2025-08-15-11-17-08-0aadb8d4.jpg",
    hoverImage: "https://i.postimg.cc/2jcdw633/Whats-App-Image-2025-08-15-11-17-08-0aadb8d4.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط KÖLN Inox Premium مع قاعدة معدنية قوية وكأس زجاجي سعة 1.5 لتر، يوفر أداء عالي لتحضير جميع الوصفات.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي – Inox",
      Capacity: "1.5 لتر",
      Power: "600 واط",
      Speeds: "3 + وظيفة Pulse",
      Color: "Inox × أسود",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k23",
    name: "KOLN Blender with Grinder 1.5L",
    category: "Kitchen Appliances",
    price: 399,
    originalPrice: 479,
    discount: 17,
    rating: 4.6,
    reviews: 29,
    image: "https://i.postimg.cc/15bpkjGQ/Whats-App-Image-2025-08-15-12-50-42-c5acb9bd.jpg",
    hoverImage: "https://i.postimg.cc/15bpkjGQ/Whats-App-Image-2025-08-15-12-50-42-c5acb9bd.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط KÖLN مزود بمطحنة إضافية للبن والتوابل، كأس زجاجي مقاوم للحرارة بسعة 1.5 لتر.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي + مطحنة",
      Capacity: "1.5 لتر",
      Power: "500 واط",
      Accessories: "مطحنة زجاجية",
      Color: "أبيض × رمادي",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k24",
    name: "KOLN Multifunction Blender 1.25L",
    category: "Kitchen Appliances",
    price: 329,
    originalPrice: 399,
    discount: 18,
    rating: 4.6,
    reviews: 26,
    image: "https://i.postimg.cc/xd2LCNpp/Whats-App-Image-2025-08-15-12-58-11-926b673c.jpg",
    hoverImage: "https://i.postimg.cc/xd2LCNpp/Whats-App-Image-2025-08-15-12-58-11-926b673c.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥤 خلاط KÖLN متعدد السرعات مع أزرار تحكم أمامية، كأس بلاستيكي قوي مع مطحنة صغيرة.",
    specs: {
      Condition: "جديد",
      Type: "خلاط كهربائي متعدد الوظائف",
      Capacity: "1.25 لتر",
      Power: "450 واط",
      Speeds: "5 مستويات + Pulse",
      Accessories: "مطحنة إضافية",
      Color: "أبيض",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k25",
    name: "KOLN Electric Iron 1200W",
    category: "Kitchen Appliances",
    price: 179,
    originalPrice: 229,
    discount: 22,
    rating: 4.6,
    reviews: 44,
    image: "https://i.postimg.cc/xd3MbjWf/Whats-App-Image-2025-08-15-13-03-37-20ca9b55.jpg",
    hoverImage: "https://i.postimg.cc/xd3MbjWf/Whats-App-Image-2025-08-15-13-03-37-20ca9b55.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "👕 مكواة كهربائية KÖLN بقوة 1200 واط، قاعدة مقاومة للالتصاق، بخفيفة وسهلة الاستعمال.",
    specs: {
      Condition: "جديد",
      Type: "مكواة كهربائية",
      Power: "1200 واط",
      Soleplate: "مضادة للالتصاق",
      Controls: "حرارة قابلة للتعديل",
      Color: "أبيض / أزرق",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k27",
    name: "Vospeed Stand Mixer 5.5L",
    category: "Kitchen Appliances",
    price: 1599,
    originalPrice: 1899,
    discount: 16,
    rating: 4.7,
    reviews: 81,
    image: "https://i.postimg.cc/W1Xgdxsk/Whats-App-Image-2025-08-26-01-17-40-257a67df.jpg",
    hoverImage: "https://i.postimg.cc/W1Xgdxsk/Whats-App-Image-2025-08-26-01-17-40-257a67df.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍞 عجانة كهربائية Vospeed Stand Mixer قوية وفعالة لتحضير جميع أنواع العجائن والخبز والحلويات. تأتي بوعاء ستانلس ستيل متين وتصميم أنيق باللون الكريمي مع أمان عالي وسهولة في الاستعمال.",
    specs: {
      Condition: "جديد",
      Type: "عجانة كهربائية (Stand Mixer)",
      Model: "Vospeed Classic",
      Color: "كريمي",
      Capacity: "5.5 لتر",
      Power: "1000 واط",
      Bowl: "ستانلس ستيل مقاوم للصدأ مع غطاء حماية",
      Speeds: "6 سرعات + خاصية Pulse",
      Accessories: "خطاف للعجين، مضرب مسطح، مضرب سلكي",
      Safety: "مانع انزلاق + نظام حماية من الحرارة",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k28",
    name: "VENEZIA Stand Mixer Premium Glass Bowl 5L",
    category: "Kitchen Appliances",
    price: 2199,
    originalPrice: 2599,
    discount: 15,
    rating: 4.8,
    reviews: 73,
    image: "https://i.postimg.cc/MG0k00rV/Whats-App-Image-2025-08-26-01-21-29-71bac148.jpg",
    hoverImage: "https://i.postimg.cc/MG0k00rV/Whats-App-Image-2025-08-26-01-21-29-71bac148.jpg",
    stockStatus: "low-stock",
    inStock: true,
    description: "✨ عجانة كهربائية Venezia Stand Mixer بتصميم فاخر باللون الأسود مع لمسة ذهبي وردي. مزودة بوعاء زجاجي محفّر متين، مثالية للعجن والخبز والحلويات.",
    specs: {
      Condition: "جديد",
      Type: "عجانة كهربائية (Stand Mixer)",
      Model: "Venezia Premium Glass Bowl",
      Color: "أسود × ذهبي وردي",
      Capacity: "5 لتر",
      Power: "1200 واط",
      Bowl: "زجاجي مقاوم للحرارة محفّر مع غطاء حماية",
      Speeds: "6 سرعات + خاصية Pulse",
      Accessories: "خطاف للعجين، مضرب سلكي، مضرب مسطح",
      Safety: "نظام حماية من الحرارة + مانع انزلاق",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k29",
    name: "BEST MARK Panini Grill",
    category: "Kitchen Appliances",
    price: 299,
    originalPrice: 379,
    discount: 21,
    rating: 4.5,
    reviews: 32,
    image: "https://i.postimg.cc/zf2QFdFL/image.png",
    hoverImage: "https://i.postimg.cc/9fkx7DcZ/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥪 آلة تحميص السندويتش والبانيني من Best Mark، تصميم أنيق، سهلة الاستعمال والتنظيف، مثالية للفطور والوجبات الخفيفة.",
    specs: {
      Condition: "جديد",
      Type: "آلة تحميص / Panini Grill",
      Power: "750 واط",
      Voltage: "220-240V / 50Hz",
      Material: "هيكل بلاستيك مقاوم للحرارة + سطح ألواح غير لاصق",
      Features: "مؤشر تشغيل/تسخين – إغلاق محكم – سهولة التخزين",
      Color: "أسود",
      Usage: "تحميص الخبز، بانيني، سندويتش، معجنات خفيفة",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k30",
    name: "VENEZIA Sandwich Grill 2000W",
    category: "Kitchen Appliances",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.7,
    reviews: 37,
    image: "https://i.postimg.cc/vBzcKVD6/image.png",
    hoverImage: "https://i.postimg.cc/TYZYC9Q4/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥪 آلة تحضير السندويشات VENEZIA متعددة الاستعمالات، مثالية للشواء، التحمير وتحضير البانيني بسرعة وسهولة.",
    specs: {
      Condition: "جديد",
      Type: "آلة سندويشات / شواية كهربائية",
      Power: "2000 واط",
      Voltage: "220-240 فولت / 50-60Hz",
      Material: "ستانلس ستيل + بلاستيك مقاوم للحرارة",
      Plates: "ألواح غير لاصقة قابلة للتنظيف",
      Usage: "تحضير السندويشات، البانيني، اللحوم والدجاج",
      Features: "مؤشر ضوئي – يد عازلة للحرارة – سهل التنظيف",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k31",
    name: "VENEZIA Panini Grill 2200W",
    category: "Kitchen Appliances",
    price: 699,
    originalPrice: 849,
    discount: 18,
    rating: 4.8,
    reviews: 34,
    image: "https://i.postimg.cc/CKw0Q68m/Whats-App-Image-2025-08-26-03-00-17-84b13e38.jpg",
    hoverImage: "https://i.postimg.cc/CKw0Q68m/Whats-App-Image-2025-08-26-03-00-17-84b13e38.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 شواية كهربائية VENEZIA متعددة الاستعمالات مع سطح شواء مزدوج غير لاصق، مثالية لتحضير السندويشات، البانيني، البرغر واللحوم بسرعة وسهولة.",
    specs: {
      Condition: "جديد",
      Type: "شواية كهربائية / بانيني غريل",
      Power: "2200 واط",
      Voltage: "220-240 فولت / 50-60Hz",
      Material: "ستانلس ستيل + ألواح غير لاصقة",
      Dimensions: "38 × 30 سم",
      Controls: "مقابض للتحكم في الحرارة والوقت",
      Features: "سطح مزدوج للشواء – مؤشر ضوئي – يد عازلة للحرارة – سهل التنظيف",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "k32",
    name: "KOLN Electric Kettle 1.7L Stainless Steel",
    category: "Kitchen Appliances",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.8,
    reviews: 45,
    image: "https://i.postimg.cc/VN53bQPr/Whats-App-Image-2025-08-26-03-05-11-ff0d8483.jpg",
    hoverImage: "https://i.postimg.cc/VN53bQPr/Whats-App-Image-2025-08-26-03-05-11-ff0d8483.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "☕ غلاية كهربائية KÖLN بسعة 1.7 لتر، مصنوعة من الستانلس ستيل المقاوم للصدأ. تصميم أنيق مع قاعدة دوارة 360°، مؤشرات ضوئية، ونظام إيقاف أوتوماتيكي عند الغليان. مثالية لتحضير الشاي، القهوة والمشروبات الساخنة بسرعة وأمان.",
    specs: {
      Condition: "جديد",
      Type: "غلاية كهربائية",
      Material: "ستانلس ستيل + بلاستيك مقاوم للحرارة",
      Capacity: "1.7 لتر",
      Power: "2200 واط",
      Color: "فضي × أسود",
      Features: "إيقاف أوتوماتيكي – قاعدة دوارة 360° – مؤشر تشغيل ضوئي – تصميم عصري",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k33",
    name: "KOLN Electric Kettle 1.8L Black White",
    category: "Kitchen Appliances",
    price: 229,
    originalPrice: 279,
    discount: 18,
    rating: 4.7,
    reviews: 41,
    image: "https://i.postimg.cc/m28X3XwQ/Whats-App-Image-2025-08-26-03-09-45-22716c81.jpg",
    hoverImage: "https://i.postimg.cc/m28X3XwQ/Whats-App-Image-2025-08-26-03-09-45-22716c81.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ غلاية كهربائية KÖLN بسعة 1.8 لتر، تصميم عصري باللونين الأسود والأبيض. مجهزة بخاصية الإيقاف الأوتوماتيكي عند الغليان، قاعدة دوارة 360°، ومؤشر تشغيل. عملية وسريعة لتحضير المشروبات الساخنة بكل أمان.",
    specs: {
      Condition: "جديد",
      Type: "غلاية كهربائية",
      Material: "بلاستيك مقاوم للحرارة + ستانلس ستيل داخلي",
      Capacity: "1.8 لتر",
      Power: "2000 واط",
      Color: "أسود × أبيض",
      Features: "إيقاف أوتوماتيكي – قاعدة دوارة 360° – مؤشر تشغيل – تصميم أنيق",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "k34",
    name: "DAMAI Grain Herb Grinder 2000W",
    category: "Kitchen Appliances",
    price: 799,
    originalPrice: 949,
    discount: 16,
    rating: 4.7,
    reviews: 30,
    image: "https://i.postimg.cc/t4m9czX6/Whats-App-Image-2025-08-26-03-18-10-d5481443.jpg",
    hoverImage: "https://i.postimg.cc/t4m9czX6/Whats-App-Image-2025-08-26-03-18-10-d5481443.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ مطحنة كهربائية عالية السرعة من ماركة DAMAI، مثالية لطحن الحبوب، التوابل والأعشاب بدقة فائقة. مصنوعة من الستانلس ستيل المتين مع أمان مزدوج. | ⚡ Broyeur électrique haute vitesse DAMAI, idéal pour moudre les céréales, épices et herbes avec une grande précision. Fabriqué en inox résistant avec double sécurité.",
    specs: {
      Condition: "جديد | Neuf",
      Power: "2000 واط | 2000W",
      Capacity: "1000 غرام | 1000g",
      Material: "ستانلس ستيل مقاوم للصدأ | Acier inoxydable",
      Speed: "28000 دورة/دقيقة | 28000 RPM",
      Features: "أداء قوي – طحن ناعم – حماية مزدوجة | Haute performance – Broyage fin – Double sécurité",
      Usage: "الحبوب، التوابل، الأعشاب | Céréales, épices, herbes",
      Year: "2024–2025",
    },
  },
  {
    id: "k35",
    name: "Stainless Steel Steamer Pot 10L 2 Levels",
    category: "Kitchen Appliances",
    price: 399,
    originalPrice: 479,
    discount: 17,
    rating: 4.8,
    reviews: 22,
    image: "https://i.postimg.cc/c4LyN8kB/Whats-App-Image-2025-08-26-03-24-59-a1b86df1.jpg",
    hoverImage: "https://i.postimg.cc/c4LyN8kB/Whats-App-Image-2025-08-26-03-24-59-a1b86df1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🥘 طنجرة ستانلس ستيل عالية الجودة للطهي بالبخار، مثالية للخضار، السمك، الكسكسي والأطباق الصحية. تصميم بطابقين مع غطاء محكم. | 🥘 Marmite vapeur en acier inoxydable de haute qualité, idéale pour légumes, poisson, couscous et plats sains. Conception à 2 niveaux avec couvercle hermétique.",
    specs: {
      Condition: "جديد | Neuf",
      Material: "ستانلس ستيل مقاوم للصدأ | Acier inoxydable",
      Capacity: "10 لتر | 10L",
      Levels: "طابقين | 2 Niveaux",
      Diameter: "28 سم | 28 cm",
      Features: "مقاومة للصدأ – توزيع حراري متساوي – سهلة التنظيف | Anti-rouille – Répartition uniforme de la chaleur – Facile à nettoyer",
      Usage: "الخضار، السمك، الكسكسي، الأطباق الصحية | Légumes, poisson, couscous, plats sains",
      Year: "2024–2025",
    },
  },

  // OVENS
  {
    id: "ov1",
    name: "VENEZIA Gas Cooker 4 Burners White",
    category: "Ovens",
    price: 899,
    originalPrice: 1099,
    discount: 18,
    rating: 4.4,
    reviews: 42,
    image: "https://i.postimg.cc/k5gRbYCM/Whats-App-Image-2025-08-14-01-28-33-5b114fcf.jpg",
    hoverImage: "https://i.postimg.cc/k5gRbYCM/Whats-App-Image-2025-08-14-01-28-33-5b114fcf.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز VENEZIA بـ 4 عيون، تصميم أنيق مع سطح أبيض سهل التنظيف، مثالي للمطبخ العصري والاستعمال اليومي.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B",
      Material: "ستانلس ستيل + مينا مقاومة للحرارة",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "أبيض",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov2",
    name: "VENEZIA Gas Cooker 4 Burners Blue",
    category: "Ovens",
    price: 949,
    originalPrice: 1149,
    discount: 17,
    rating: 4.4,
    reviews: 39,
    image: "https://i.postimg.cc/Jz5vMm5Y/Whats-App-Image-2025-08-14-01-29-00-ca158aa1.jpg",
    hoverImage: "https://i.postimg.cc/Jz5vMm5Y/Whats-App-Image-2025-08-14-01-29-00-ca158aa1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز VENEZIA بـ 4 عيون، تصميم أنيق بغطاء أزرق معدني عصري، قوة وأمان مع سهولة التنظيف.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Blue",
      Material: "ستانلس ستيل + مينا مقاومة للحرارة",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "أزرق معدني",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov3",
    name: "LITIMAT Gas Cooker 4 Burners Black",
    category: "Ovens",
    price: 859,
    originalPrice: 999,
    discount: 14,
    rating: 4.4,
    reviews: 35,
    image: "https://i.postimg.cc/y6SVBggf/Whats-App-Image-2025-08-14-01-29-17-0075d5c3.jpg",
    hoverImage: "https://i.postimg.cc/y6SVBggf/Whats-App-Image-2025-08-14-01-29-17-0075d5c3.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز LITIMAT بـ 4 عيون، عملي واقتصادي، لون أسود أنيق مع أزرار تحكم أمامية دقيقة، مثالي للعائلات.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 4 عيون",
      Brand: "LITIMAT",
      Model: "LT-4B",
      Material: "مينا حرارية مقاومة",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "أسود",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov4",
    name: "VENEZIA Gas Cooker 4 Burners Black",
    category: "Ovens",
    price: 929,
    originalPrice: 1099,
    discount: 15,
    rating: 4.4,
    reviews: 37,
    image: "https://i.postimg.cc/JzK8Kjvh/Whats-App-Image-2025-08-14-01-32-17-1fab317c.jpg",
    hoverImage: "https://i.postimg.cc/JzK8Kjvh/Whats-App-Image-2025-08-14-01-32-17-1fab317c.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز VENEZIA أسود بغطاء معدني، 4 عيون قوية مع تصميم عصري وأنيق، مثالي للاستعمال اليومي والمطابخ الحديثة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Black",
      Material: "مينا حرارية مقاومة",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "أسود",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov5",
    name: "LITIMAT Gas Cooker 4 Burners Grey",
    category: "Ovens",
    price: 849,
    originalPrice: 999,
    discount: 15,
    rating: 4.4,
    reviews: 33,
    image: "https://i.postimg.cc/pd6HMR2b/Whats-App-Image-2025-08-14-01-55-36-c7f357a1.jpg",
    hoverImage: "https://i.postimg.cc/pd6HMR2b/Whats-App-Image-2025-08-14-01-55-36-c7f357a1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز Litimat رمادي بغطاء علوي، 4 عيون عملية واقتصادية، سهل الاستعمال والتنظيف.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 4 عيون",
      Brand: "LITIMAT",
      Model: "LT-4B-Grey",
      Material: "مينا حرارية مقاومة",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "رمادي",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov6",
    name: "KOLN Gas Cooker 3 Burners Black Gold",
    category: "Ovens",
    price: 799,
    originalPrice: 949,
    discount: 16,
    rating: 4.4,
    reviews: 31,
    image: "https://i.postimg.cc/Dzm9gH1C/Whats-App-Image-2025-08-14-01-39-56-03aba269.jpg",
    hoverImage: "https://i.postimg.cc/Dzm9gH1C/Whats-App-Image-2025-08-14-01-39-56-03aba269.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز KOLN بـ 3 عيون، سطح زجاجي أسود مع ديزاين ذهبي وأنيق، قوة وأداء عالي للمطبخ العصري.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 3 عيون",
      Brand: "KOLN",
      Model: "KLN-3B",
      Material: "سطح زجاج حراري",
      Ignition: "يدوي",
      Safety: "صمام أمان",
      Color: "أسود + ذهبي",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov7",
    name: "VENEZIA Gas Cooker 2 Burners Brown",
    category: "Ovens",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.4,
    reviews: 28,
    image: "https://i.postimg.cc/pVKgqDnt/Whats-App-Image-2025-08-14-01-51-53-a8d6cdb8.jpg",
    hoverImage: "https://i.postimg.cc/pVKgqDnt/Whats-App-Image-2025-08-14-01-51-53-a8d6cdb8.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز VENEZIA صغير الحجم بـ 2 عيون، تصميم بني تقليدي أنيق، اقتصادي ومثالي للاستعمال السريع.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 2 عيون",
      Brand: "VENEZIA",
      Model: "VZ-2B-Brown",
      Material: "مينا حرارية مقاومة",
      Ignition: "يدوي",
      Color: "بني",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov8",
    name: "KOLN Gas Cooker 2 Burners Silver",
    category: "Ovens",
    price: 529,
    originalPrice: 629,
    discount: 16,
    rating: 4.4,
    reviews: 26,
    image: "https://i.postimg.cc/fbZ3S7XT/Whats-App-Image-2025-08-14-02-01-36-3f293df2.jpg",
    hoverImage: "https://i.postimg.cc/fbZ3S7XT/Whats-App-Image-2025-08-14-02-01-36-3f293df2.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز KOLN بـ 2 عيون، تصميم ستانلس سيلفر أنيق وصغير الحجم، عملي جداً للمطابخ الصغيرة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 2 عيون",
      Brand: "KOLN",
      Model: "KLN-2B-Silver",
      Material: "ستانلس ستيل مقاوم للصدأ",
      Ignition: "يدوي",
      Color: "فضي",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov9",
    name: "KOLN Gas Cooker 2 Burners Black Glass",
    category: "Ovens",
    price: 579,
    originalPrice: 699,
    discount: 17,
    rating: 4.4,
    reviews: 29,
    image: "https://i.postimg.cc/0j6r1VgZ/Whats-App-Image-2025-08-14-02-01-58-a5c08856.jpg",
    hoverImage: "https://i.postimg.cc/0j6r1VgZ/Whats-App-Image-2025-08-14-02-01-58-a5c08856.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز KOLN بسطح زجاجي أسود مع 2 عيون قوية، تصميم أنيق جداً مع لمسة عصرية واحترافية.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز – 2 عيون",
      Brand: "KOLN",
      Model: "KLN-2B-Glass",
      Material: "سطح زجاج مقوى",
      Ignition: "يدوي",
      Color: "أسود زجاجي",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov10",
    name: "LITIMAT Electric Cooker 2 Burners",
    category: "Ovens",
    price: 699,
    originalPrice: 849,
    discount: 18,
    rating: 4.4,
    reviews: 24,
    image: "https://i.postimg.cc/BQKth7Bn/Whats-App-Image-2025-08-14-02-03-43-074812e7.jpg",
    hoverImage: "https://i.postimg.cc/BQKth7Bn/Whats-App-Image-2025-08-14-02-03-43-074812e7.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ كوكوط كهربائي بـ 2 عيون Litimat، مثالي للطبخ السريع في غياب الغاز، تصميم ستانلس ستيل مقاوم للحرارة.",
    specs: {
      Condition: "جديد",
      Type: "كوكوط كهربائي – 2 عيون",
      Brand: "LITIMAT",
      Model: "LT-E2",
      Power: "2000 واط",
      Voltage: "220-240V",
      Burners: "2",
      Material: "ستانلس ستيل",
      Warranty: "سنة واحدة",
      Year: "2024",
    },
  },
  {
    id: "ov11",
    name: "VENEZIA Built-in Gas Hob 4 Burners Black",
    category: "Ovens",
    price: 1190,
    originalPrice: 1390,
    discount: 14,
    rating: 4.4,
    reviews: 32,
    image: "https://i.postimg.cc/Jh2G6fvt/Whats-App-Image-2025-08-14-02-06-11-f7695f45.jpg",
    hoverImage: "https://i.postimg.cc/Jh2G6fvt/Whats-App-Image-2025-08-14-02-06-11-f7695f45.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز مدمج بـ 4 عيون VENEZIA باللون الأسود، إشعال أوتوماتيكي وأمان عالي، مثالي للمطابخ الحديثة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-BuiltIn",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "سطح زجاج حراري",
      Safety: "صمام أمان + مانع تسرب",
      Warranty: "2 سنوات",
      Year: "2024",
    },
  },
  {
    id: "ov12",
    name: "VENEZIA Built-in Gas Hob 4 Burners Steel",
    category: "Ovens",
    price: 1290,
    originalPrice: 1490,
    discount: 13,
    rating: 4.4,
    reviews: 30,
    image: "https://i.postimg.cc/Y0pK19RF/Whats-App-Image-2025-08-14-02-07-58-94486d20.jpg",
    hoverImage: "https://i.postimg.cc/Y0pK19RF/Whats-App-Image-2025-08-14-02-07-58-94486d20.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز VENEZIA ستانلس ستيل بـ 4 عيون، جودة عالية، سهل التنظيف وصالح للاستعمال المكثف.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Steel",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "ستانلس ستيل مقاوم للصدأ",
      Safety: "صمام أمان",
      Warranty: "2 سنوات",
      Year: "2024",
    },
  },
  {
    id: "ov13",
    name: "VENEZIA Built-in Gas Hob 4 Burners Inox",
    category: "Ovens",
    price: 1290,
    originalPrice: 1490,
    discount: 13,
    rating: 4.4,
    reviews: 28,
    image: "https://i.postimg.cc/MpQwJXs7/Whats-App-Image-2025-08-14-02-10-31-b5bcfb77.jpg",
    hoverImage: "https://i.postimg.cc/MpQwJXs7/Whats-App-Image-2025-08-14-02-10-31-b5bcfb77.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز VENEZIA Inox بـ 4 عيون مع شعلة كبيرة للطبخ السريع، عملي وأنيق مع أزرار جانبية.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Inox",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "Inox مصقول",
      Safety: "صمام أمان + مانع تسرب",
      Warranty: "2 سنوات",
      Year: "2024",
    },
  },
  {
    id: "ov14",
    name: "VENEZIA Built-in Gas Hob 5 Burners Black Glass",
    category: "Ovens",
    price: 1400,
    originalPrice: 1600,
    discount: 13,
    rating: 4.4,
    reviews: 34,
    image: "https://i.postimg.cc/BndZ76vB/Whats-App-Image-2025-08-26-21-36-12-10dbc27b.jpg",
    hoverImage: "https://i.postimg.cc/BndZ76vB/Whats-App-Image-2025-08-26-21-36-12-10dbc27b.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز VENEZIA بـ 5 عيون سطح زجاجي أسود، قوة وأداء عالي، مجهز بأزرار أمامية وأمان كامل.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج 5 عيون",
      Brand: "VENEZIA",
      Model: "VZ-5B-BlackGlass",
      Burners: "5",
      Material: "ستانلس ستيل + زجاج",
      Safety: "نظام أمان كامل + إيقاف تلقائي",
      SizesPrices: "50/75 سم 1400dh | 50/90 سم 1500dh",
      Warranty: "سنتان",
      Year: "2024",
    },
  },
  {
    id: "ov15",
    name: "VENEZIA Built-in Gas Hob 5 Burners Pro",
    category: "Ovens",
    price: 1400,
    originalPrice: 1600,
    discount: 13,
    rating: 4.4,
    reviews: 31,
    image: "https://i.postimg.cc/SNcpQrQC/Whats-App-Image-2025-08-26-21-41-04-a90c6c38.jpg",
    hoverImage: "https://i.postimg.cc/SNcpQrQC/Whats-App-Image-2025-08-26-21-41-04-a90c6c38.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز احترافي VENEZIA بـ 5 عيون مع تصميم بروفيشنال، مثالي للمطابخ الكبيرة والاستعمال الكثيف.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 5 عيون",
      Brand: "VENEZIA",
      Model: "VZ-5B-Pro",
      Ignition: "أوتوماتيكي",
      Burners: "5",
      Material: "ستانلس ستيل + زجاج",
      Safety: "نظام أمان كامل + إيقاف تلقائي",
      SizesPrices: "50/75 سم 1400dh | 50/90 سم 1500dh",
      Warranty: "2 سنوات",
      Year: "2024",
    },
  },
  {
    id: "ov16",
    name: "VENEZIA Built-in Gas Hob 4 Burners Inox 2025",
    category: "Ovens",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.4,
    reviews: 27,
    image: "https://i.postimg.cc/yYJxW1Qd/Whats-App-Image-2025-08-14-02-33-35-e7267d6a.jpg",
    hoverImage: "https://i.postimg.cc/yYJxW1Qd/Whats-App-Image-2025-08-14-02-33-35-e7267d6a.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز مدمج VENEZIA بـ 4 عيون من الستانلس ستيل، إشعال أوتوماتيكي وأمان كامل.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Inox",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "ستانلس ستيل",
      Safety: "صمام أمان",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov17",
    name: "VENEZIA Built-in Gas Hob 5 Burners Blue",
    category: "Ovens",
    price: 1490,
    originalPrice: 1690,
    discount: 12,
    rating: 4.4,
    reviews: 25,
    image: "https://i.postimg.cc/dVr0mWKc/Whats-App-Image-2025-08-14-02-34-39-8205b8ba.jpg",
    hoverImage: "https://i.postimg.cc/dVr0mWKc/Whats-App-Image-2025-08-14-02-34-39-8205b8ba.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "💎 تصميم عصري باللون الأزرق، فورنو غاز بـ 5 عيون مثالي للمطابخ الكبيرة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 5 عيون",
      Brand: "VENEZIA",
      Model: "VZ-5B-Blue",
      Ignition: "أوتوماتيكي",
      Burners: "5",
      Material: "مينا + ستانلس",
      Safety: "مانع تسرب",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov18",
    name: "VENEZIA Built-in Gas Hob 4 Burners Silver",
    category: "Ovens",
    price: 1240,
    originalPrice: 1440,
    discount: 14,
    rating: 4.4,
    reviews: 24,
    image: "https://i.postimg.cc/wvfxTZDL/Whats-App-Image-2025-08-14-02-45-58-f23dad35.jpg",
    hoverImage: "https://i.postimg.cc/wvfxTZDL/Whats-App-Image-2025-08-14-02-45-58-f23dad35.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "✨ فورنو غاز VENEZIA فضي، سهل التنظيف، مجهز بـ 4 عيون احترافية.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Silver",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "ستانلس + مينا",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov19",
    name: "VENEZIA Built-in Gas Hob 5 Burners Black Flower",
    category: "Ovens",
    price: 1490,
    originalPrice: 1690,
    discount: 12,
    rating: 4.4,
    reviews: 23,
    image: "https://i.postimg.cc/Pr8fT6Jv/Whats-App-Image-2025-08-14-02-46-28-73f6f2cb.jpg",
    hoverImage: "https://i.postimg.cc/Pr8fT6Jv/Whats-App-Image-2025-08-14-02-46-28-73f6f2cb.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🌸 سطح زجاجي أسود مع زخرفة أنيقة، فورنو غاز بـ 5 عيون، مثالي للمطابخ الحديثة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 5 عيون",
      Brand: "VENEZIA",
      Model: "VZ-5B-BlackFlower",
      Ignition: "أوتوماتيكي",
      Burners: "5",
      Material: "زجاج حراري",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov20",
    name: "VENEZIA Built-in Gas Hob 4 Burners Black Glass",
    category: "Ovens",
    price: 1190,
    originalPrice: 1390,
    discount: 14,
    rating: 4.4,
    reviews: 22,
    image: "https://i.postimg.cc/DmVTST0J/Whats-App-Image-2025-08-14-02-55-38-a46c624e.jpg",
    hoverImage: "https://i.postimg.cc/DmVTST0J/Whats-App-Image-2025-08-14-02-55-38-a46c624e.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚫ سطح زجاج أسود أنيق، فورنو غاز بـ 4 عيون، إشعال أوتوماتيكي مع أمان عالي.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-BlackGlass",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "زجاج حراري",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov21",
    name: "VENEZIA Built-in Gas Hob 4 Burners Pro",
    category: "Ovens",
    price: 1340,
    originalPrice: 1540,
    discount: 13,
    rating: 4.4,
    reviews: 21,
    image: "https://i.postimg.cc/G368FTsY/Whats-App-Image-2025-08-14-03-00-43-1bcda6d1.jpg",
    hoverImage: "https://i.postimg.cc/G368FTsY/Whats-App-Image-2025-08-14-03-00-43-1bcda6d1.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "💎 فورنو غاز VENEZIA Inox Pro، احترافي مع شعلة ثلاثية للطبخ السريع.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 4 عيون",
      Brand: "VENEZIA",
      Model: "VZ-4B-Pro",
      Ignition: "أوتوماتيكي",
      Burners: "4",
      Material: "ستانلس ستيل",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov22",
    name: "VENEZIA Built-in Gas Hob 3 Burners Black",
    category: "Ovens",
    price: 990,
    originalPrice: 1190,
    discount: 17,
    rating: 4.4,
    reviews: 20,
    image: "https://i.postimg.cc/L6zXjCSK/Whats-App-Image-2025-08-14-14-04-06-cbcd75dd.jpg",
    hoverImage: "https://i.postimg.cc/L6zXjCSK/Whats-App-Image-2025-08-14-14-04-06-cbcd75dd.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ فورنو غاز VENEZIA بـ 3 عيون، عملي وصغير الحجم للمطابخ المتوسطة.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 3 عيون",
      Brand: "VENEZIA",
      Model: "VZ-3B-Black",
      Ignition: "أوتوماتيكي",
      Burners: "3",
      Material: "زجاج أسود",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov23",
    name: "VENEZIA Built-in Gas Hob 5 Burners Inox",
    category: "Ovens",
    price: 1540,
    originalPrice: 1740,
    discount: 11,
    rating: 4.4,
    reviews: 22,
    image: "https://i.postimg.cc/6Q15BFrR/Whats-App-Image-2025-08-14-14-07-15-32a56a2a.jpg",
    hoverImage: "https://i.postimg.cc/6Q15BFrR/Whats-App-Image-2025-08-14-14-07-15-32a56a2a.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فورنو غاز VENEZIA Inox بـ 5 عيون، تصميم فاخر، أمان كامل، وملائم للاستعمال المكثف.",
    specs: {
      Condition: "جديد",
      Type: "فرن غاز مدمج – 5 عيون",
      Brand: "VENEZIA",
      Model: "VZ-5B-Inox",
      Ignition: "أوتوماتيكي",
      Burners: "5",
      Material: "ستانلس ستيل",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov24",
    name: "VENEZIA Electric Oven 45L",
    category: "Ovens",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    rating: 4.7,
    reviews: 64,
    image: "https://i.postimg.cc/PrH2nzCC/Whats-App-Image-2025-08-25-17-59-15-a7952917.jpg",
    hoverImage: "https://i.postimg.cc/PrH2nzCC/Whats-App-Image-2025-08-25-17-59-15-a7952917.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ فرن كهربائي VENEZIA بسعة 45 لتر، مثالي للخبز والشوي والتحميص، مجهز بمؤقت وحرارة قابلة للتعديل حتى 250°C مع مروحة توزيع للحرارة لطهي متساوي.",
    specs: {
      Capacity: "45 لتر",
      Power: "2000 واط",
      Controls: "3 أزرار (حرارة – مؤقت – وظائف)",
      Temperature: "قابلة للتعديل حتى 250°C",
      Fan: "مروحة لتوزيع الهواء الساخن (Convection)",
      Door: "زجاج مقاوم للحرارة",
      Color: "فضي × أسود",
      Dimensions: "55 × 38 × 33 سم (تقريباً)",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov25",
    name: "VENEZIA Built-in Microwave 25L Stainless Steel",
    category: "Ovens",
    price: 2390,
    originalPrice: 2790,
    discount: 14,
    rating: 4.7,
    reviews: 41,
    image: "https://i.postimg.cc/j5ZdqhsR/Whats-App-Image-2025-08-25-18-11-20-60e174ea.jpg",
    hoverImage: "https://i.postimg.cc/j5ZdqhsR/Whats-App-Image-2025-08-25-18-11-20-60e174ea.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "🍽️ ميكروويف مدمج VENEZIA بسعة 25 لتر، تصميم أنيق بالستانلس ستيل مع واجهة زجاجية سوداء. مجهز ببرامج طهي متعددة، مؤقت رقمي، ووظيفة إذابة التجميد السريع. مثالي للمطابخ الحديثة.",
    specs: {
      Type: "ميكروويف مدمج (Built-in)",
      Capacity: "25 لتر",
      Power: "900 واط (5 مستويات)",
      Controls: "زر دوّار + أزرار أمامية + شاشة رقمية",
      Functions: "تسخين – طهي – إذابة تجميد",
      Door: "باب زجاجي مقاوم للحرارة بفتح جانبي",
      Color: "فضي (ستانلس ستيل) × أسود",
      Dimensions: "59 × 39 × 38 سم تقريباً",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov26",
    name: "VENEZIA Built-in Microwave 23L Black",
    category: "Ovens",
    price: 2190,
    originalPrice: 2490,
    discount: 12,
    rating: 4.8,
    reviews: 34,
    image: "https://i.postimg.cc/52gxS3CL/Whats-App-Image-2025-08-25-18-15-50-d6e46680.jpg",
    hoverImage: "https://i.postimg.cc/52gxS3CL/Whats-App-Image-2025-08-25-18-15-50-d6e46680.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ ميكروويف مدمج VENEZIA باللون الأسود الأنيق، سعة 23 لتر مع برامج طهي متعددة ووظيفة إذابة التجميد، شاشة رقمية وواجهة تحكم سهلة. مثالي للمطابخ العصرية.",
    specs: {
      Type: "ميكروويف مدمج (Built-in)",
      Capacity: "23 لتر",
      Power: "800 واط (5 مستويات)",
      Controls: "أزرار + زر دوّار + شاشة رقمية",
      Functions: "تسخين – طهي – إذابة تجميد – مؤقت",
      Door: "باب زجاجي أسود مقاوم للحرارة",
      Color: "أسود",
      Dimensions: "59 × 39 × 36 سم تقريباً",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov27",
    name: "VENEZIA Built-in Electric Oven 70L",
    category: "Ovens",
    price: 3990,
    originalPrice: 4590,
    discount: 13,
    rating: 4.7,
    reviews: 53,
    image: "https://i.postimg.cc/CLKJKM40/image.png",
    hoverImage: "https://i.postimg.cc/Bv3KXMGF/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن كهربائي مدمج VENEZIA بسعة كبيرة وتصميم عصري باللون الأسود مع زجاج مقاوم للحرارة. مجهز بمروحة توزيع هواء وشواية مدمجة لطهي متجانس، مثالي للخبز والشواء والتحميص.",
    specs: {
      Type: "فرن كهربائي مدمج",
      Capacity: "70 لتر",
      Brand: "VENEZIA",
      Programs: "متعددة – تسخين علوي/سفلي + مروحة + شواية",
      Controls: "مقابض دوارة + شاشة رقمية",
      Power: "220-240V – 50Hz",
      Light: "إضاءة داخلية هالوجين",
      Door: "زجاج مزدوج مقاوم للحرارة",
      Color: "أسود مع لمسة ستانلس",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov28",
    name: "VENEZIA Built-in Electric Oven 60L Black Glass",
    category: "Ovens",
    price: 3590,
    originalPrice: 4090,
    discount: 12,
    rating: 4.7,
    reviews: 46,
    image: "https://i.postimg.cc/ZYvps9jC/image.png",
    hoverImage: "https://i.postimg.cc/xTY8GqZr/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن مدمج كهربائي من VENEZIA بسعة 60 لتر، تصميم أنيق باللون الأسود والزجاج المقوى، مجهز بمروحة حرارية لتوزيع مثالي للحرارة، مع وظائف متعددة للطبخ والشوي والخبز. مثالي للمطابخ العصرية.",
    specs: {
      Type: "فرن مدمج كهربائي",
      Capacity: "60 لتر",
      Brand: "VENEZIA",
      Width: "60 سم",
      Door: "باب زجاج مزدوج مقاوم للحرارة",
      Safety: "نظام أمان ضد الحرارة الزائدة",
      Programs: "شوي – خبز – مروحة حرارية",
      Power: "كهربائي (220-240V)",
      Light: "داخلية LED",
      Material: "ستانلس ستيل + زجاج أسود",
      Color: "أسود مع لمسة معدنية",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov29",
    name: "KUMTEL Built-in Electric Oven 60L",
    category: "Ovens",
    price: 3290,
    originalPrice: 3790,
    discount: 13,
    rating: 4.6,
    reviews: 37,
    image: "https://i.postimg.cc/RZ5RL1BS/Whats-App-Image-2025-08-25-18-21-16-b65fa457.jpg",
    hoverImage: "https://i.postimg.cc/RZ5RL1BS/Whats-App-Image-2025-08-25-18-21-16-b65fa457.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ فرن مدمج من KUMTEL بسعة 60 لتر، تصميم أنيق باللون الأسود مع واجهة ستانلس ستيل، مجهز بمروحة لتوزيع الهواء الساخن بشكل متساوي، مع وظائف متعددة للشوي، الخبز والتحميص. اختيار عملي وعصري لمطبخك.",
    specs: {
      Type: "فرن مدمج كهربائي",
      Capacity: "60 لتر",
      Brand: "KUMTEL",
      Width: "60 سم",
      Programs: "شوي – خبز – تحميص – مروحة حرارية",
      Door: "باب زجاج مزدوج مقاوم للحرارة",
      Power: "كهربائي (220-240V)",
      Light: "داخلية",
      Material: "ستانلس ستيل + زجاج أسود",
      Color: "أسود / فضي (ستانلس ستيل)",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },
  {
    id: "ov30",
    name: "DREAM Double Gas Oven",
    category: "Ovens",
    price: 2490,
    originalPrice: 2890,
    discount: 14,
    rating: 4.6,
    reviews: 29,
    image: "https://i.postimg.cc/Kjnqr1ws/image.png",
    hoverImage: "https://i.postimg.cc/Kjnqr1ws/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز مزدوج DREAM مثالي للعائلات والمطاعم الصغيرة، مجهز ببابين زجاجيين مقاومين للحرارة لمراقبة الطهي، تصميم معدني متين، يعمل بالغاز ويوفر توزيع حراري متوازن لطهي سريع وفعّال.",
    specs: {
      Type: "فرن غاز مزدوج – غاز بوتان/بروبان",
      Capacity: "2 × 35 لتر تقريباً",
      Doors: "بابين زجاجيين مزدوجين مقاومين للحرارة",
      Handles: "مقابض عازلة للحرارة",
      Ignition: "يدوي مع أمان ضد تسرب الغاز",
      Material: "هيكل معدني مطلي ضد الصدأ",
      Dimensions: "70 × 55 × 50 سم (تقريباً)",
      Usage: "منزلي / مهني (مطاعم صغيرة)",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "ov31",
    name: "DREAM Double Gas Oven Brown",
    category: "Ovens",
    price: 2690,
    originalPrice: 3090,
    discount: 13,
    rating: 4.6,
    reviews: 33,
    image: "https://i.postimg.cc/C5zMRV21/image.png",
    hoverImage: "https://i.postimg.cc/C5zMRV21/image.png",
    stockStatus: "in-stock",
    inStock: true,
    description: "🔥 فرن غاز مزدوج DREAM باللون البني الكلاسيكي، مثالي للاستعمال المنزلي مع تصميم قوي وأبواب زجاجية مقاومة للحرارة. يوفر توزيع حراري متوازن لطهي سريع وفعّال مع خزان سفلي للتخزين.",
    specs: {
      Type: "فرن غاز مزدوج – غاز بوتان/بروبان",
      Capacity: "2 × 40 لتر تقريباً",
      Doors: "بابين علويين زجاجيين + بابين سفليين للتخزين",
      Handles: "مقابض عازلة للحرارة",
      Ignition: "يدوي مع صمام أمان",
      Material: "هيكل معدني مطلي ضد الصدأ",
      Color: "بني غامق (كلاسيكي)",
      Dimensions: "80 × 55 × 50 سم (تقريباً)",
      Usage: "منزلي – عائلي",
      Warranty: "سنة واحدة",
      Year: "2024–2025",
    },
  },
  {
    id: "ov32",
    name: "VENEZIA Countertop Electric Oven 45L",
    category: "Ovens",
    price: 1390,
    originalPrice: 1690,
    discount: 18,
    rating: 4.4,
    reviews: 52,
    image: "https://i.postimg.cc/sDRffYhn/Whats-App-Image-2025-08-14-14-14-02-144d961a.jpg",
    hoverImage: "https://i.postimg.cc/sDRffYhn/Whats-App-Image-2025-08-14-14-14-02-144d961a.jpg",
    stockStatus: "in-stock",
    inStock: true,
    description: "⚡ فرن كهربائي صغير متعدد الوظائف، مثالي للخبز والتسخين السريع، بسعة 45 لتر.",
    specs: {
      Type: "فرن كهربائي صغير – كونترتوب",
      Brand: "VENEZIA",
      Model: "VZ-EL45",
      Capacity: "45 لتر",
      Programs: "شواية + خبز + تسخين",
      Power: "2000 واط",
      Warranty: "سنتان",
      Year: "2024–2025",
    },
  },

  // DISHWASHERS
  {
    id: "d1",
    name: "Miele G 7100 Built-under Dishwasher",
    category: "Dishwashers",
    price: 15499,
    originalPrice: 16999,
    discount: 8,
    rating: 4.9,
    reviews: 42,
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=800&auto=format&fit=crop",
    stockStatus: "in-stock",
    inStock: true,
    description: "EcoPower and 3D MultiFlex tray. Up to 15 place settings in perfect silence.",
    specs: {
      Places: "14",
      "Energy Class": "A",
      "Noise Level": "44 dB",
    },
  },
  {
    id: "d2",
    name: "Bosch Serie 6 SMS6HCI00E Dishwasher",
    category: "Dishwashers",
    price: 8999,
    originalPrice: 10499,
    discount: 14,
    rating: 4.6,
    reviews: 67,
    image: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?q=80&w=800&auto=format&fit=crop",
    stockStatus: "in-stock",
    inStock: true,
    description: "PerfectDry with Zeolith for perfect drying even on plastic items.",
    specs: {
      Places: "13",
      "Energy Class": "B",
      "Noise Level": "42 dB",
    },
  },
  {
    id: "d3",
    name: "Samsung DW60BG735 Zone Booster",
    category: "Dishwashers",
    price: 7499,
    rating: 4.4,
    reviews: 30,
    image: "https://images.unsplash.com/photo-1584622781564-1d987f7333c1?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1581622558663-b2e33377dfb2?q=80&w=800&auto=format&fit=crop",
    stockStatus: "low-stock",
    inStock: true,
    description: "Zone Booster deep cleans even the most heavily soiled dishes.",
    specs: {
      Places: "14",
      Programs: "9",
    },
  },

  // SMALL APPLIANCES
  {
    id: "sa1",
    name: "Dyson V15 Detect Cordless Vacuum",
    category: "Small Appliances",
    price: 7499,
    originalPrice: 8499,
    discount: 12,
    rating: 4.9,
    reviews: 345,
    image: "https://images.unsplash.com/photo-1558317374-067fb5f30001?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?q=80&w=800&auto=format&fit=crop",
    stockStatus: "in-stock",
    inStock: true,
    description: "Laser illumination reveals hidden dust. Acoustic piezo sensor measures and displays particles.",
    specs: {
      Runtime: "60 min",
      Filtration: "HEPA",
      Suction: "230 AW",
    },
  },
  {
    id: "sa2",
    name: "Philips PerfectCare Elite Steam Generator",
    category: "Small Appliances",
    price: 1499,
    originalPrice: 1799,
    discount: 17,
    rating: 4.5,
    reviews: 178,
    image: "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1558317374-067fb5f30001?q=80&w=800&auto=format&fit=crop",
    stockStatus: "low-stock",
    inStock: true,
    description: "OptimalTEMP technology — no burns possible on any fabric at any temperature setting.",
    specs: {
      Power: "2400 W",
      Pressure: "6.5 bar",
      Tank: "1.5 L",
    },
  },

  // COOKWARE
  {
    id: "cw1",
    name: "Le Creuset Signature Casserole 28cm",
    category: "Cookware",
    price: 3499,
    originalPrice: 3999,
    discount: 12,
    rating: 5.0,
    reviews: 88,
    image: "https://images.unsplash.com/photo-1584286594519-75691062b322?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?q=80&w=800&auto=format&fit=crop",
    stockStatus: "in-stock",
    inStock: true,
    description: "The classic round casserole for slow-cooked stews and perfectly braised meats.",
    specs: {
      Material: "Enameled Cast Iron",
      Diameter: "28 cm",
      Capacity: "6.3 L",
    },
  },
  {
    id: "cw2",
    name: "Tefal Titanium Excellence Pan Set 5pcs",
    category: "Cookware",
    price: 1899,
    originalPrice: 2299,
    discount: 17,
    rating: 4.6,
    reviews: 215,
    image: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1584286594519-75691062b322?q=80&w=800&auto=format&fit=crop",
    stockStatus: "in-stock",
    inStock: true,
    description: "Professional titanium non-stick coating. Compatible with all hobs including induction.",
    specs: {
      Pieces: "5",
      Coating: "Titanium",
      Compatible: "All hobs",
    },
  },
  {
    id: "cw3",
    name: "Zwilling Pro Knife Set 7 Pieces",
    category: "Cookware",
    price: 2799,
    originalPrice: 3299,
    discount: 15,
    rating: 4.8,
    reviews: 143,
    image: "https://images.unsplash.com/photo-1593618998160-e34014e67546?q=80&w=800&auto=format&fit=crop",
    hoverImage: "https://images.unsplash.com/photo-1604329760661-e71dc83f8f26?q=80&w=800&auto=format&fit=crop",
    stockStatus: "low-stock",
    inStock: true,
    description: "Ice-hardened FRIODUR blade stays sharper longer. Ergonomic handles for precision.",
    specs: {
      Pieces: "7",
      Steel: "FRIODUR Stainless",
    },
  },
];

// ─── Promotional Products (subset with big discounts) ────────────────────────
export const promotionProductIds = [
  "r2", "r3", "r6", "r8",
  "w1", "w2", "w4", "w5",
  "t1", "t2", "t3",
  "af1", "af2",
  "c1", "c3", "c4",
  "k1", "k4", "k26", "k28", "k31", "k34",
  "ov3", "ov5", "ov14", "ov15", "ov27", "ov28",
];

// ─── Packs ────────────────────────────────────────────────────────────────────
export const packs: Pack[] = [
  {
    id: "pack1",
    name: "Pack Cuisine & Salon Connecté",
    products: [
      "VENEZIA Refrigerator 200L Bottom Freezer",
      "VENEZIA Electric Oven 45L",
      'VENEZIA Google TV 4K QLED 55"',
    ],
    images: [
      "https://i.postimg.cc/wBCCdRK0/image.png",
      "https://i.postimg.cc/PrH2nzCC/Whats-App-Image-2025-08-25-17-59-15-a7952917.jpg",
      "https://i.postimg.cc/j2sk7z7Q/Whats-App-Image-2025-08-13-23-08-33-9019ba30.jpg",
    ],
    originalPrice: 7797,
    packPrice: 6999,
    discount: 10,
    description: "Un pack harmonieux pour équiper votre cuisine et votre espace TV avec des essentiels modernes et élégants.",
    badge: "Best Seller",
  },
  {
    id: "pack2",
    name: "Pack Barista & Pâtisserie",
    products: [
      "KOLN Espresso Machine 15 Bar",
      "Vospeed Stand Mixer 5.5L",
      "VENEZIA Panini Grill 2200W",
    ],
    images: [
      "https://i.postimg.cc/wBKzkPKc/Whats-App-Image-2025-08-16-01-48-24-01fbfdc2.jpg",
      "https://i.postimg.cc/W1Xgdxsk/Whats-App-Image-2025-08-26-01-17-40-257a67df.jpg",
      "https://i.postimg.cc/CKw0Q68m/Whats-App-Image-2025-08-26-03-00-17-84b13e38.jpg",
    ],
    originalPrice: 3997,
    packPrice: 3299,
    discount: 17,
    description: "Le pack idéal pour les amateurs de café, pâtisserie et snacks maison avec un style premium.",
    badge: "Hot Deal",
  },
  {
    id: "pack3",
    name: "Pack TV & Pause Café",
    products: [
      'VENEZIA Google TV 75" 4K QLED',
      "KOLN Espresso Machine 15 Bar",
      "VENEZIA Sandwich Grill 2000W",
    ],
    images: [
      "https://i.postimg.cc/76YW2kss/Whats-App-Image-2025-08-13-23-14-17-f27182fe.jpg",
      "https://i.postimg.cc/wBKzkPKc/Whats-App-Image-2025-08-16-01-48-24-01fbfdc2.jpg",
      "https://i.postimg.cc/vBzcKVD6/image.png",
    ],
    originalPrice: 9797,
    packPrice: 8699,
    discount: 11,
    description: "Profitez d’un grand écran immersif avec une vraie ambiance snack & café à la maison.",
    badge: "Lifestyle",
  },
  {
    id: "pack4",
    name: "Pack Lavage & Confort",
    products: [
      "VENEZIA R1000 Front Load 9kg Steam",
      "KOLN Electric Water Heater 50L",
      "KOLN Electric Iron 1200W",
    ],
    images: [
      "https://i.postimg.cc/3JrQFW80/image.png",
      "https://i.postimg.cc/g2BfbdM0/image.png",
      "https://i.postimg.cc/xd3MbjWf/Whats-App-Image-2025-08-15-13-03-37-20ca9b55.jpg",
    ],
    originalPrice: 5577,
    packPrice: 4799,
    discount: 14,
    description: "Un pack pratique pour le quotidien: lavage, eau chaude et repassage dans une seule offre.",
    badge: "New",
  },
  {
    id: "pack5",
    name: "Pack Chef Maison Premium",
    products: [
      "VENEZIA Stand Mixer OU-6118 7L",
      "KOLN Pro Inox Blender 2L",
      "VENEZIA Air Fryer Digital 5L",
    ],
    images: [
      "https://i.postimg.cc/5yTvPJQY/Whats-App-Image-2025-08-26-01-25-03-2f34e6cc.jpg",
      "https://i.postimg.cc/DfB6M6pv/Whats-App-Image-2025-08-15-11-04-03-ef568ce0.jpg",
      "https://i.postimg.cc/dQnqK4dw/Whats-App-Image-2025-08-16-01-42-46-9cf2c3db.jpg",
    ],
    originalPrice: 5097,
    packPrice: 4299,
    discount: 16,
    description: "Un trio puissant pour préparer pâtes, smoothies, sauces et repas croustillants comme un chef.",
    badge: "Premium",
  },
  {
    id: "pack6",
    name: "Pack Maison Familiale",
    products: [
      "VENEZIA Refrigerator 420L Inverter",
      "VENEZIA X1000 Front Load 10kg",
      "VENEZIA Wall Mounted Hood 60cm Black",
    ],
    images: [
      "https://i.postimg.cc/8PLj8Mqn/image.png",
      "https://i.postimg.cc/WbN23XxZ/image.png",
      "https://i.postimg.cc/xCcsXx95/Whats-App-Image-2025-08-26-20-17-19-5902d6ec.jpg",
    ],
    originalPrice: 11288,
    packPrice: 9899,
    discount: 12,
    description: "Des équipements grands formats et élégants pour une cuisine familiale moderne et performante.",
    badge: "Family",
  },
  {
    id: "pack7",
    name: "Pack Air Fry & Grill",
    products: [
      "VENEZIA Air Fryer 3L",
      "VENEZIA Air Fryer Digital 5L",
      "VENEZIA Electric Barbecue 70cm",
    ],
    images: [
      "https://i.postimg.cc/BvDS935V/Whats-App-Image-2025-08-16-01-28-07-c6c43117.jpg",
      "https://i.postimg.cc/dQnqK4dw/Whats-App-Image-2025-08-16-01-42-46-9cf2c3db.jpg",
      "https://i.postimg.cc/qRcbqdGy/Whats-App-Image-2025-08-19-17-39-35-a2eaddfc.jpg",
    ],
    originalPrice: 3297,
    packPrice: 2799,
    discount: 15,
    description: "Le combo parfait pour cuisiner sainement, croustillant et convivial à la maison.",
    badge: "Trending",
  },
  {
    id: "pack8",
    name: "Pack Espresso Master",
    products: [
      "VENEZIA Capsule Coffee Machine",
      "KOLN Espresso Pro Touch 20 Bar",
      "KOLN Automatic Espresso Machine Grinder 20 Bar",
    ],
    images: [
      "https://i.postimg.cc/HLZFHmBx/Whats-App-Image-2025-08-16-01-51-39-dfb75095.jpg",
      "https://i.postimg.cc/8C9wtzZh/Whats-App-Image-2025-08-16-02-08-03-988e4bbe.jpg",
      "https://i.postimg.cc/K8c9YVKg/Whats-App-Image-2025-08-16-02-03-16-92fb5d84.jpg",
    ],
    originalPrice: 5697,
    packPrice: 4899,
    discount: 14,
    description: "Trois styles de machines à café pour créer votre coin barista maison selon vos envies.",
    badge: "Limited",
  },
  {
    id: "pack9",
    name: "Pack Nettoyage & Eau Pure",
    products: [
      "VENEZIA Industrial Vacuum Cleaner 20L",
      "KOLN Home Vacuum Cleaner 2L",
      "VENEZIA Water Purifier 5 Stages",
    ],
    images: [
      "https://i.postimg.cc/8cQGQDzv/Whats-App-Image-2025-08-19-15-40-08-f3329ac0.jpg",
      "https://i.postimg.cc/jdTTMs90/Whats-App-Image-2025-08-19-15-39-27-470381b0.jpg",
      "https://i.postimg.cc/BZHs58mB/Whats-App-Image-2025-08-16-02-16-58-eec921de.jpg",
    ],
    originalPrice: 3747,
    packPrice: 3199,
    discount: 15,
    description: "Gardez votre maison propre et votre eau plus pure avec ce pack pratique et utile au quotidien.",
    badge: "Smart Choice",
  },
  {
    id: "pack10",
    name: "Pack TV & Tech Vision",
    products: [
      'VENEZIA Google TV 75" 4K QLED',
      'VENEZIA Google TV 4K QLED 55"',
      'KÖLN Android 14 Smart TV 32"',
    ],
    images: [
      "https://i.postimg.cc/76YW2kss/Whats-App-Image-2025-08-13-23-14-17-f27182fe.jpg",
      "https://i.postimg.cc/j2sk7z7Q/Whats-App-Image-2025-08-13-23-08-33-9019ba30.jpg",
      "https://i.postimg.cc/sD9Hwxk6/Whats-App-Image-2025-08-13-23-24-11-ab721ddf.jpg",
    ],
    originalPrice: 22297,
    packPrice: 19499,
    discount: 13,
    description: "Un pack orienté divertissement avec trois écrans complémentaires pour le salon, la chambre ou le bureau.",
    badge: "VIP",
  },
];

// ─── Store Locations ──────────────────────────────────────────────────────────
export const storeLocations: StoreLocation[] = [
  {
    id: "casa",
    city: "Casablanca",
    address: "Boulevard Zerktouni, Espace Commercial ElectroPlaza, Casablanca 20000",
    hours: "Lun–Sam: 9h00 – 19h00  |  Dim: 10h00 – 17h00",
    phone: "+212 5 22 000 000",
    mapUrl: "https://maps.google.com/?q=Casablanca+Morocco",
  },
  {
    id: "marrakech",
    city: "Marrakech",
    address: "Avenue Mohammed VI, Centre Commercial Carrefour, Marrakech 40000",
    hours: "Lun–Sam: 9h00 – 19h30  |  Dim: 10h00 – 17h00",
    phone: "+212 5 24 000 000",
    mapUrl: "https://maps.google.com/?q=Marrakech+Morocco",
  },
];

// ─── Helpers ──────────────────────────────────────────────────────────────────
function enrichProduct(product: Product): Product {
  return {
    ...product,
    isPromotion:
      promotionProductIds.includes(product.id) ||
      Boolean(product.discount && product.discount > 0),
  };
}

// ─── Utility functions ────────────────────────────────────────────────────────
export const PRODUCTS_PER_PAGE = 10;

export function getProductsByCategory(category: string): Product[] {
  return products
    .filter((p) => p.category.toLowerCase() === category.toLowerCase())
    .map(enrichProduct);
}

export function getRelatedProducts(productId: string, category: string, count = 6): Product[] {
  return products
    .filter((p) => p.id !== productId && p.category === category)
    .map(enrichProduct)
    .slice(0, count);
}

export function getPaginatedProducts(items: Product[], page: number, perPage = PRODUCTS_PER_PAGE) {
  return items.slice((page - 1) * perPage, page * perPage);
}

export function getTotalPages(items: Product[], perPage = PRODUCTS_PER_PAGE) {
  return Math.ceil(items.length / perPage);
}

export function getPromotionProducts(): Product[] {
  return products
    .filter((p) => promotionProductIds.includes(p.id) || Boolean(p.discount && p.discount > 0))
    .map(enrichProduct);
}

export function getProductById(id: string): Product | undefined {
  const product = products.find((p) => p.id === id);
  return product ? enrichProduct(product) : undefined;
}
export function getAllProducts(): Product[] {
  return products.map(enrichProduct);
}